### ISSUE TITLE
Cannot use iperf on Mininet with OpenVSwitch and datapath=user

### ISSUE THREAD

**Issue by zixuanli3566** [esnet/iperf#958] opened 2020-01-28 23:31 UTC
I installed my own routing rules on OpenVSwitch on Mininet and set datapath=user. Host 1 can Host 2 can successfully ping each other but when I use iperf it's always timed out. If I remove "datapath=user", I could use iperf but I would have to use "datapath=user" because of my own routing rules.

How to solve this issue? Any help is appreciated!

**Comment by bmah888** [comment] 2020-04-13 21:33
Sorry, I have no idea how to make this work (actually I'm not sure what the problem is, although I bet someone more familiar with mininet would).  Naively, it feels to me like this is more of a mininet issue than an iperf3 issue.

**Comment by bmah888** [comment] 2020-04-20 15:57
We'd need further details to help, and we don't have a lot of experience running iperf3 in mininet.  CLosing for now.  Feel free to re-open or open a new issue if you can provide more details.

**Closed by bmah888** 2020-04-20 15:57 UTC
Labels: question
