### ISSUE TITLE
Usage of the libiperf callback API

### ISSUE THREAD

**Issue by vladimiroltean** [esnet/iperf#502] opened 2017-01-20 17:16 UTC
Hi,
I am trying to create a custom wrapper around an iPerf client/server setup with the following modifications:
* server: for each received packet in iperf_recv() (per stream), get timestamp (packet arrival) difference from the last one. I want to compute the probability density function of the stream latency.
* client: print the exact same info in iperf_reporter_callback() as it is right now, but in a different format.

Here are some concerns:

* I am looking at iperf_api.h and examples/mic.c and trying to understand how to make use of them. Since in iperf_api.h, struct iperf_test, iperf_stream_result, iperf_interval_results and iperf_stream are only declared but not defined, I am not able to access their content. Instead I suppose I should only use the getters/setters provided. But how can I do this when:

* Implementing a callback looks like a case of defining my own function like e.g. void iperf_reporter_callback(struct iperf_test * test) {}. But once I do this, the old function in iperf_api.c no longer gets called, and part of iperf's default behavior stops working. No problem, I say, while copying the iperf_reporter_callback() code from iperf_api.c to mic.c. But no, wait, this is starting to draw lots of dependencies from iperf_api.c, and I stop seeing the point of linking with libiperf.

Can you provide a clear-cut usage scenario for the API, where something really meaningful is done inside the callbacks? At the moment, the only option that I see is to fork iperf3 and perform the modifications inline.

Thanks,
Vladimir

**Comment by bmah888** [comment] 2017-01-26 00:24
I haven't actually played with the library calls from an external application, so I can't really comment on this, at least not without further research.  I wonder if anyone else has tried something similar?

**Comment by lengletclement** [comment] 2017-02-28 15:15
Hi,

I'm trying to do the same thing. Same issue. Same conclusion. iperf_api seems to be designed to do very basic task.

**Comment by bmah888** [comment] 2017-03-10 03:59
I definitely agree with @lengletclement's last statement.  The iperf3 API was designed to support integrating the iperf3 functionality to another specific network performance utility.  My guess is additional work could have gone into making the API more general-purpose, but that's what we have now.

Running iperf3 as a subprocess is probably the best approach at this point.

Closing.

**Closed by bmah888** 2017-03-10 03:59 UTC
Labels: question
