### ISSUE TITLE
Sending UDP traffic without server

### ISSUE THREAD

**Issue by jose205** [esnet/iperf#284] opened 2015-07-24 07:01 UTC
Hi,

Anybody has compiled/development iperf3 for working in an UDP environment without server?
Thanks in advance.

**Comment by jose205** [comment] 2015-08-05 10:49
Anybody? I´ll check the traffic sent with the router counters.

**Comment by bmah888** [comment] 2015-08-06 14:51
Duplicate of #194.

**Closed by bmah888** 2015-08-06 14:51 UTC
Labels: duplicate
