### ISSUE TITLE
UDP summary transfer and bandwidth always 0 (iperf3.1)

### ISSUE THREAD

**Issue by rvandepu** [esnet/iperf#314] opened 2015-10-23 14:16 UTC
Hi,

When running UDP tests the summary for 'Transfer' and 'Bandwidth' are always zero on server side.

```
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.0.192, port 42683
[  5] local 192.168.0.243 port 5201 connected to 192.168.0.192 port 59222
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  1.08 MBytes  9.04 Mbits/sec  0.076 ms  0/138 (0%)
[  5]   1.00-2.00   sec  1.20 MBytes  10.0 Mbits/sec  0.071 ms  0/153 (0%)
[  5]   2.00-3.00   sec  1.19 MBytes  9.96 Mbits/sec  0.067 ms  0/152 (0%)
[  5]   3.00-4.00   sec  1.20 MBytes  10.0 Mbits/sec  0.064 ms  0/153 (0%)
[  5]   4.00-5.00   sec  1.19 MBytes  9.96 Mbits/sec  0.086 ms  0/152 (0%)
[  5]   5.00-6.00   sec  1.20 MBytes  10.0 Mbits/sec  0.066 ms  0/153 (0%)
[  5]   6.00-7.00   sec  1.20 MBytes  10.0 Mbits/sec  0.065 ms  0/153 (0%)
[  5]   7.00-8.00   sec  1.19 MBytes  9.96 Mbits/sec  0.061 ms  0/152 (0%)
[  5]   8.00-9.00   sec  1.20 MBytes  10.0 Mbits/sec  0.085 ms  0/153 (0%)
[  5]   9.00-10.00  sec  1.19 MBytes  9.96 Mbits/sec  0.060 ms  0/152 (0%)
[  5]  10.00-10.04  sec  0.00 Bytes  0.00 bits/sec  0.060 ms  0/0 (nan%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-10.04  sec  0.00 Bytes  0.00 bits/sec  0.060 ms  0/1511 (0%)
```

Running iperf3.1

**Comment by ABCD1225** [comment] 2015-11-10 12:17
Same with Iperf 3.0.11-64bit running on Windows with UDP tests

**Comment by bmah888** [comment] 2015-11-16 19:54
This is indeed a bug, a duplicate of issue #293.  For various reasons, it's not easy to fix the way the test workflow is currently implemented.  :-(

**Closed by bmah888** 2015-11-16 19:54 UTC
Labels: duplicate

**Comment by rajkiranjoshi** [comment] 2016-08-24 13:16
Well, this seems to re-appear in 3.1.3 as well :(

**Comment by bogemon** [comment] 2017-05-14 21:56
Hi is there a fix for this bug ?

**Comment by bmah888** [comment] 2017-05-15 17:47
Mostly.  As of iperf 3.2 (not yet released, but you can try the code on the tip of the master branch if you know how to compile it), the server will report on what it received (see issue #560).

**Comment by sarravic** [comment] 2021-03-29 13:20
@bmah888  currently, 3.1.3 version is available for arm64 in iperf download page. I need a newer version with a fix for this issue. Can you point me to the location to download it?

**Comment by lovelysuman** [comment] 2021-06-14 07:34
Observing this issue on windows vms for iperf3 UDP traffic 

iperf3 Version:


Server listening on 8088                                                                                                        
-----------------------------------------------------------                                                                     
Accepted connection from 10.48.130.113, port 50077                                                                              
[  5] local 10.48.130.114 port 8088 connected to 10.48.130.113 port 58059                                                       
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams                                            
[  5]   0.00-1.01   sec   117 KBytes   952 Kbits/sec  2645.112 ms  0/100 (0%)                                                   
[  5]   1.01-2.01   sec   128 KBytes  1.05 Mbits/sec  2.346 ms  0/109 (0%)                                                      
[  5]   2.01-3.01   sec   128 KBytes  1.05 Mbits/sec  0.024 ms  0/109 (0%)                                                      
[  5]   3.01-4.01   sec   128 KBytes  1.05 Mbits/sec  0.046 ms  0/109 (0%)                                                      
[  5]   4.01-5.01   sec   128 KBytes  1.05 Mbits/sec  0.027 ms  0/109 (0%)                                                      
[  5]   5.01-6.01   sec   129 KBytes  1.06 Mbits/sec  0.015 ms  0/110 (0%)                                                      
[  5]   6.01-7.01   sec   128 KBytes  1.05 Mbits/sec  0.021 ms  0/109 (0%)                                                      
[  5]   7.01-8.01   sec   128 KBytes  1.05 Mbits/sec  0.014 ms  0/109 (0%)                                                      
[  5]   8.01-9.01   sec   128 KBytes  1.05 Mbits/sec  0.016 ms  0/109 (0%)                                                      
[  5]   9.01-10.01  sec   129 KBytes  1.06 Mbits/sec  0.014 ms  0/110 (0%)                                                      
[  5]  10.01-10.04  sec  1.17 KBytes   299 Kbits/sec  0.016 ms  0/1 (0%)                                                        
- - - - - - - - - - - - - - - - - - - - - - - - -                                                                               
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams                                            
[  5]   0.00-10.04  sec  **0.00 Bytes  0.00 bits/sec**  0.016 ms  0/1084 (0%)

**Comment by davidBar-On** [comment] 2021-06-14 07:58
New iperf3 versions executable for Windows are available at  [https://files.budman.pw/](https://files.budman.pw/) or [https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/](https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/)  (in both download is from the same site).  Note that this is **not an official iperf3** site and I didn't try to use executable from it, but I saw some recommendations about using it.

**Comment by lovelysuman** [comment] 2021-06-14 10:33
Working fine. Thanks @davidBar-On
