### ISSUE TITLE
time-to-live for multicast

### ISSUE THREAD

**Issue by DD1984** [esnet/iperf#262] opened 2015-04-16 11:49 UTC
pls, support this option, it need to test multicast through router (it decrease ttl, and do not pass mc to client if ttl==0)

**Comment by nomel** [comment] 2015-04-16 22:00
This is correct behavior. A TTL value of zero is restricted to the host so will never get onto the wire. See
http://www.tldp.org/HOWTO/Multicast-HOWTO-2.html
and its references.

**Comment by bmah888** [comment] 2015-05-08 18:17
Multicast tests aren't supported in iperf3.  There's an open enhancement request for that functionality, it's issue #27.  Marking this issue a duplicate of that one.

**Closed by bmah888** 2015-05-08 18:17 UTC
Labels: duplicate
