### ISSUE TITLE
iperf3 - issues while installing

### ISSUE THREAD

**Issue by chaganti75** [esnet/iperf#490] opened 2016-12-13 15:12 UTC
When I am running make, it is giving me the error. Any help is appreciated.
==============
make  all-am
/bin/bash ../libtool  --tag=CC    --mode=link gcc -g -g -O2 -Wall  -g  -o iperf3 iperf3-main.o libiperf.la -lsctp -lnsl -lsocket -lresolv -lrt -lm
libtool: link: gcc -g -g -O2 -Wall -g -o .libs/iperf3 iperf3-main.o  ./.libs/libiperf.so -lsctp -lnsl -lsocket -lresolv -lrt -lm -R/usr/local/lib
Undefined                       first referenced
 symbol                             in file
htonll                              ./.libs/libiperf.so
ntohll                              ./.libs/libiperf.so
ld: fatal: symbol referencing errors. No output written to .libs/iperf3
collect2: ld returned 1 exit status
*** Error code 1
make: Fatal error: Command failed for target `iperf3'
Current working directory /opt/iperf/iperf-3.1.4/src
*** Error code 1
make: Fatal error: Command failed for target `all'

**Comment by bmah888** [comment] 2016-12-15 19:12
Need some more details on what OS/hardware you're doing, also what version of iperf3 and arguments (if any) to configure.

**Comment by bmah888** [comment] 2017-03-17 19:13
Symptoms similar to #454, still don't have enough details in this bug (see my previous comment) to know whether they're the same or not.  If I don't get some more information I'll just mark this as a duplicate of #454.

**Closed** 2017-03-28 23:38 UTC
Labels: bug
