### ISSUE TITLE
Disable Nagle 

### ISSUE THREAD

**Issue by mercury1986** [esnet/iperf#434] opened 2016-06-17 11:11 UTC
Hi 

I tested iperf 3.1.2 and 3.1.3 on a windows 2008 R2 with following settings:

iperf3.exe -c 10.1.5.203 -l 6B -t 5 -N

In the wireshark file you can see that the packets with a 6B payload were sending only the first second. Then you can see bigger packets. It seems that the -N setting works only for the first time interval (0.00-1.01 sec). 
Or there are any changes on the windows 2008 r2 to do to disable the nagle algorithm?

Thanks
mercury

[iperf-tcpnodelay.zip](https://github.com/esnet/iperf/files/320304/iperf-tcpnodelay.zip)

**Comment by bmah888** [comment] 2016-11-17 18:12
I have no idea why Windows behaves this way, and iperf3 isn't officially supported on Windows anyway.  Maybe try asking the party who created the Windows executable you're using?

**Comment by bmah888** [comment] 2017-03-17 21:24
So I read this issue again and thought about it a bit.  I think it's working as designed.

Nagel's algorithm coalesces a bunch of small writes and sends them out as a single packet.  Disabling Nagel's algorithm means that if a small write can be sent out, it won't be delayed.

If you already have a bunch of small writes buffered up (perhaps because the TCP congestion window hasn't opened up yet), my understanding is that they'll be sent together, as if they were coalesced in the sending socket buffer.  Disabling Nagel's algorithm does *not* mean that the sizes of writes to sockets will be preserved in outgoing packets, it just means that it won't artificially delay data in small writes.

Based on your description of what's happening on the wire, I think that the Windows 2008 TCP is doing the right thing.  In any case I don't think it's an iperf3 issue, so going to close this.

**Closed by bmah888** 2017-03-17 21:24 UTC
Labels: question
