### ISSUE TITLE
Extremely high Jitter value reported by iPerf 3.10.1

### ISSUE THREAD

**Issue by d3c1978** [esnet/iperf#1212] opened 2021-09-27 18:32 UTC
# Context

* Version of iperf3: 3.10.1

* Hardware:
  Samsung Galaxy S21 (ARM64) (Client), Intel Xeon 64-bit (Server)

* Operating system (and distribution, if any):
  Android 11 (Client), Ubuntu 18.04 Server (Server)

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
  iperf3 cross compiled for Android and Ubuntu servers using standard compilers (toolchain provided by Android for client and standard GCC for server)

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate._

# Bug Report
   Running a UDP Reverse Stream occassionally produces a very high Jitter value which is much longer than the test itself. This does not happen all the time, but about 8% of the runs.
   On first thought, this seemed to be related to bug #

* Expected Behavior
  Jitter value is realistic in all cases

* Actual Behavior
  The initial jitter (and sometimes after the initial interval) shows up as being much longer (occassionally we saw the value representing over 24 hours).

`iperf3 -c iperfserver -R -u -P 1 -b 6M --port 6366
Connecting to host iperfserver, port 6366
Reverse mode, remote host iperfserver is sending
[  5] local 2222:ffff:xxxx:yyyy:aaaa:bbbb:cccc:dddd port 37242 connected to 2222:1111:aaa:bbbb:cccc:dddd:eeee:ffff port 6366
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec   228 KBytes  1.87 Mbits/sec  3408823.110 ms  527590/527761 (1e+02
[  5]   1.00-2.00   sec   365 KBytes  2.99 Mbits/sec  6.670 ms  -273/0 (0
[  5]   2.00-3.00   sec   446 KBytes  3.66 Mbits/sec  3.619 ms  -334/0 (0
[  5]   3.00-4.00   sec   310 KBytes  2.54 Mbits/sec  4.861 ms  -232/0 (0
[  5]   4.00-5.00   sec   254 KBytes  2.08 Mbits/sec  3.571 ms  -190/0 (0
[  5]   5.00-6.00   sec   256 KBytes  2.10 Mbits/sec  17.492 ms  -192/0 (0
[  5]   6.00-7.00   sec   265 KBytes  2.16 Mbits/sec  6.195 ms  -198/0 (0
[  5]   7.00-8.00   sec   311 KBytes  2.55 Mbits/sec  6.391 ms  -233/0 (0
[  5]   8.00-9.00   sec   590 KBytes  4.84 Mbits/sec  2.988 ms  -442/0 (0
[  5]   9.00-10.00  sec   281 KBytes  2.30 Mbits/sec  4.323 ms  -210/0 (0
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-10.06  sec  7.20 MBytes  6.00 Mbits/sec  0.000 ms  0/5518 (0
[SUM]  0.0-10.1 sec  2474 datagrams received out-of-order
[  5]   0.00-10.00  sec  3.23 MBytes  2.71 Mbits/sec  4.323 ms  525286/527761 (1e+02

iperf Done.
`

This seems related to similar issues (#1182, #1123 and #990) but has some difference from their client reports. Please feel free to duplicate if it is exactly the same issue.

**Comment by davidBar-On** [comment] 2021-09-28 08:52
@d3c1978, assuming your are building iperf3 yourself, can your try running with the **client** built from [this branch in my personal repository](https://github.com/davidBar-On/iperf/tree/issue-1123-udp-ooo-corrupt-sequence-number)?

This branch includes a fix based on the analysis done in #1123.  It also includes debug messages that should show whether the issue is fixed.  On the client side, when there is no problem you should see the debug message:
    `*** [TEST]: CONNECT RECEIVED sz=4, buf=39383736, ...`

If the issue is fixed, in tests that should have failed you should see **several** of the messages:
    `*** [TEST]: CONNECT RECEIVED sz=4, buf=<something>, ...`

The last message should be `*** [TEST]: CONNECT RECEIVED sz=4, buf=39383736, ...`.

Can you test and see whether the issue is fixed?  In any case, whether the issue is fixed or not, can you send the client's output from a problematic test case?

**Comment by davidBar-On** [comment] 2021-10-20 06:32
@d3c1978, thanks for the update.
You also don't see the `*** [TEST]: CONNECT RECEIVED ....` messages?  I am asking since if the PR fixes the issue then the issue will not be reproduced, but these messages will be displayed for the fixed cases.

**Comment by d3c1978** [comment] 2022-01-01 17:09
@davidBar-On, so sorry I didn't see this message until now. Yes, I do see the *** [TEST]: CONNECT RECEIVED ... message in responses (but don't see the original issue in the reports. So, I belive this did fix the issue. Thank you so much for it, and wish you a very happy 2022.

**Comment by davidBar-On** [comment] 2022-01-08 12:23
@d3c1978 thanks.  I have now submitted the suggested fix in PR #1260.

**Comment by bmah888** [comment] 2022-02-14 21:18
Believed fixed by #1260.

**Closed by bmah888** 2022-02-14 21:18 UTC
