### ISSUE TITLE
iPerf-3.1.3 udp test blocked on windows 7

### ISSUE THREAD

**Issue by sepcity** [esnet/iperf#662] opened 2017-10-28 10:48 UTC
I download iperf-3.1.3 (windows 64 version) from https://iperf.fr/iperf-download.php#windows
run "iperf3.exe -s" command  on one of my pc.
run "iperf3.exe -c 192.168.5.8 -u" command one another pc.
kill the iperf client's process before it complete.
run "iperf3.exe -c 192.168.5.8 -u" command again on the same pc.
the iperf client will block permanently.

**Comment by bmah888** [comment] 2017-10-30 17:04
Windows is not an officially supported platform, and the iperf3 developers at ESnet has no control over the contents of any of the Windows executables provided by third parties.

I'm not able to reproduce this problem using a current version of iperf3 on any of the officially supported platforms.

Closing this for now as (so far) there doesn't appear to be an issue with iperf3 itself.  You could perhaps ask on the iperf-dev@google-groups.com mailing list whether anyone can make you a more recent iperf3 executable for Windows (version 3.1.3 is pretty old now).  I'm told it builds under Cygwin, but can't give any more specifics about how to go about doing this.

**Closed by bmah888** 2017-10-30 17:04 UTC
