### ISSUE TITLE
--get-server-output does not return result to the client for some cases 

### ISSUE THREAD

**Issue by prachichoudhary22** [esnet/iperf#1081] opened 2020-11-26 08:59 UTC
* Version of iperf3: 3.1.3

* Hardware: Ubuntu 16.04

# Bug Report
When the client is run with '--get-server-output', '--json' option and '--json' option on server, the client gets an error "Error - unable to receive results" for server output in some cases when bits per second on server side is 0.

* Expected Behavior
The client should have received the server output json after the completion of the test.

* Actual Behavior
The client gets an error "Error - unable to receive results" for server output.

* Steps to Reproduce
On the server, run "iperf3 -s --json"
On the client, run "iperf3 -c server_ip --json -u -w 4m -i 1 --bandwidth 1000000000 -t 60 --length 30000 --get-server-output"

**Comment by davidBar-On** [comment] 2020-11-28 07:46
This is probably a **duplicate of #1080** (with the same root cause that the requested window size is too high).

**Comment by bmah888** [comment] 2020-11-30 19:08
I agree this is probably a duplicate of a previously reported issue.

**Closed by bmah888** 2020-11-30 19:08 UTC
Labels: duplicate

**Comment by prachichoudhary22** [comment] 2020-12-01 04:41
This error is mostly seen when the bits per second at the receiver side is 0. In that case, when "--json" flag is used, the client fails with error "Unable to receive outputs".

#1080 and #1081 both are related to this particular flag "--json", the difference being for #1080 , the output is not fetched when receiver shows 0 bits per second. In #1081, the issue is "--udp-counters-64bit" in combination with "--json" and "--get-server-output".

FYI: The behavior is observed even when -w 4m was not configured.
