### ISSUE TITLE
are these results real?

### ISSUE THREAD

**Issue by babatundebusari** [esnet/iperf#602] opened 2017-06-19 02:06 UTC
i have 2 VMs both ubuntu 16.04LTS and ran iperf3  to check bandwidth speed and got the below results

```
Connecting to host 10.10.10.10, port 5201
[  4] local 10.10.10.11 port 44978 connected to 10.10.10.10 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  1.07 GBytes  9.19 Gbits/sec    1    700 KBytes
[  4]   1.00-2.00   sec  1.06 GBytes  9.09 Gbits/sec    0    768 KBytes
[  4]   2.00-3.00   sec  1.09 GBytes  9.34 Gbits/sec    0    788 KBytes
[  4]   3.00-4.00   sec  1.00 GBytes  8.62 Gbits/sec    0    823 KBytes
[  4]   4.00-5.00   sec  1.01 GBytes  8.64 Gbits/sec    0    850 KBytes
[  4]   5.00-6.00   sec  1.08 GBytes  9.28 Gbits/sec    0    895 KBytes
[  4]   6.00-7.00   sec  1.15 GBytes  9.92 Gbits/sec    0    905 KBytes
[  4]   7.00-8.00   sec  1.15 GBytes  9.91 Gbits/sec    0    909 KBytes
[  4]   8.00-9.00   sec  1.08 GBytes  9.27 Gbits/sec    0    909 KBytes
[  4]   9.00-10.00  sec  1.01 GBytes  8.68 Gbits/sec    0    912 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  10.7 GBytes  9.19 Gbits/sec    1             sender
[  4]   0.00-10.00  sec  10.7 GBytes  9.19 Gbits/sec                  receiver
```

The VMs are on the same host and network connection is on 1GE port, so how come i am getting those kind of results? 

```
iperf 3.0.11
Linux 10.10.10.11 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```

**Comment by TheRealDJ** [comment] 2017-06-19 16:38
Looks like internal VM network is 10GbE. Since they are both on the same physical host, the data doesn't need to transverse real Ethernet.

**Comment by bmah888** [comment] 2017-06-19 18:58
Thanks @TheRealDJ , I agree that's probably the right explanation.  Going to close this issue.  Also, it was really a user question not a bug report or enhancement request.

**Closed by bmah888** 2017-06-19 18:58 UTC
Labels: question
