### ISSUE TITLE
iperf3: error - unable to receive parameters from client

### ISSUE THREAD

**Issue by askrinnik** [esnet/iperf#530] opened 2017-03-19 14:16 UTC
I downloaded iperf-3.1.3-win64 to my Windows 10 PC and ran:
`iperf3.exe -s -i 5`
It was said:
`Server listening on 5201`

Then I installed iperf for Android to my Samsung Galaxy S4 mini and ran : 
`-c 192.168.0.2 -p 5201`
Server said:
`iperf3: error - unable to receive parameters from client:`

What did I do wrong?

**Comment by hoang-tranviet** [comment] 2017-03-20 17:50
Hello,
One way to determine the issue is to add verbose and debug parameter (-V -d) on server and client.
Rgds

**Comment by bmah888** [comment] 2017-03-20 21:11
What version is "iperf for Android"?  In particular is it some flavor of iperf2 or iperf3?  The two are not compatible (you can't have an iperf2 client connect to an iperf3 server, or vice versa).

**Comment by hoang-tranviet** [comment] 2017-03-21 10:30
Hi Bruce,
This is a common issue for newcomers,
Do you think that iperf3 should detect if the remote peer is using an old version and report to user explicitly?

**Comment by bmah888** [comment] 2017-03-21 16:25
This is basically a duplicate of #74.  In our experience this doesn't happen real often (and we specifically mention it in several places in the iperf3 documentation).  (I'm not saying people _never_ run into this problem, just that in our experience it's not common.)  Sorry for the confusion and good luck!

**Closed by bmah888** 2017-03-21 16:25 UTC
Labels: duplicate, enhancement

**Comment by miguel-sudo** [comment] 2020-02-20 13:34
Hi 
Check ther version of server and client.
The versions should be same.

**Comment by schemacs** [comment] 2021-11-12 08:05
I had the same issue today, but I found out another program(redis-server) was also sending some data to the server port.

client:
```
$ iperf3 -p 7020 -c 192.168.1.1
iperf3: error - unable to receive control message: Connection reset by peer
```

server:
```
$ iperf3 -s -p 7020
-----------------------------------------------------------
Server listening on 7020
-----------------------------------------------------------
WARNING:  Size of data read does not correspond to offered length
iperf3: error - unable to receive parameters from client:
```

I found out this after I try to bind another a simple http server to 7020:
```
$ python -m SimpleHTTPServer 7020
Serving HTTP on 0.0.0.0 port 7020 ...
192.168.1.2 - - [12/Nov/2021 15:57:57] code 400, message Bad request syntax ('*2')
192.168.1.2- - [12/Nov/2021 15:57:57] "*2" 400 -
```
