### ISSUE TITLE
Server support for multicast (-u no longer allowed for server)

### ISSUE THREAD

**Issue by fearlessbeaver** [esnet/iperf#260] opened 2015-04-08 00:42 UTC
I was able to do multicast testing with iperf2 but no longer with iperf3 since the "-s" and "-u" options are no longer compatible. If I combine them I get an error saying "-u" is "client only". If I omit the "-u" the multicast group is not joined (i.e. IGMP join request is not sent).

Is the intent to no longer support multicast testing from the server/listener side?

Jason

<b>Using iperf2:</b>
<pre>
[root@machine1 ~]# iperf --version
iperf version 2.0.4 (7 Apr 2008) pthreads
[root@machine1 ~]# iperf -s -u -B 239.239.242.2 -p 15000 -i 1 # Server/Listener
------------------------------------------------------------
Server listening on UDP port 15000
Binding to local address 239.239.242.2
Joining multicast group  239.239.242.2
Receiving 1470 byte datagrams
UDP buffer size: 16.0 MByte (default)
------------------------------------------------------------
</pre>

<b>Using iperf3:</b> (the latest code in the repo)
<pre>
[root@machine2 ~]# iperf3 -s -B 239.239.242.2 -p 15000 -i 1 # Server/Listener
-----------------------------------------------------------
Server listening on 15000
-----------------------------------------------------------
</pre>

**Comment by stanhu** [comment] 2015-04-24 00:58
Somehow -u became a client-only option in 987b4323164fb83d1f9adcb9a9339ec3495e558c. As far as I can tell, this was not the intention.

**Comment by nomel** [comment] 2015-04-24 10:36
According to this: https://github.com/esnet/iperf/issues/193

There is no multicast support in iperf3.

**Comment by bmah888** [comment] 2015-05-08 18:16
The enhancement request for multicast support is really #27.  I'm going to declare this issue a duplicate of that one.

```-u``` doesn't work on the server because it is not needed.  The client communicates what protocol to use (and other test parameters) to the server over a TCP control connection; it is not necessary to specify a protocol explicitly to the server at start-up time.  This is a different model of interaction from iperf 2.

**Closed by bmah888** 2015-05-08 18:16 UTC
Labels: duplicate
