### ISSUE TITLE
Problems with iperf on WAN lines with high latency

### ISSUE THREAD

**Issue by jonimessi** [esnet/iperf#515] opened 2017-02-23 10:59 UTC
I am using iperf3 (version 3.1.6 on FreeBSD) in conjunction with BWCTLD (version 1.5.4). On wan lines with high latency I get often errors in measruments via "bwctl -T iperf3 ... "

WARNING:  Size of data read does not correspond to offered length
iperf3: error - unable to receive results: Resource temporarily unavailable

Does anyone know whats the reason for the Warning causing the iperf3 error?
Are there any parameters which can be switched to have a stable test on wan lines with high latency?

Thanks in advance!

**Comment by bmah888** [comment] 2017-03-15 18:22
Does iperf3 work fine on its own, without bwctl?  Trying to see where the problem is, whether it's in iperf3 or bwctl.  I'm not sure how much bwctl is used on FreeBSD.

We use iperf3 to test cross-country and trans-Atlantic links, so it certainly works in those kinds of environments, although the test systems are generally Linux not FreeBSD.  My first guess is that this difference is not significant.

**Comment by jonimessi** [comment] 2017-03-16 08:44
I seems that it is working now. I configured the sync_fuzz and die_by parameter in bwctl config. After that the bwctl time window stay long enough open to finish the iperf3 tasks. So I think problem is a timing problem of bwctl cause of the high latency...

**Comment by bmah888** [comment] 2017-03-16 16:03
Sounds good...I'll close this issue for now but feel free to reopen if you think there's something that's iperf3 related.  Thanks!

**Closed by bmah888** 2017-03-16 16:03 UTC
Labels: question
