### ISSUE TITLE
Iperf3 shows extremely low throughput but wget shows throughput differently

### ISSUE THREAD

**Issue by smalleni** [esnet/iperf#463] opened 2016-09-24 23:55 UTC
Hi,
Running iperf3 TCP between two VMs I see extremely low throughput(around 2Mbps). However, wgetting a file I see aroung 900Mbps. I believe HTTP works over TCP, so how is it that we see such huge difference. Any help is appreciated.

**Comment by taismi** [comment] 2016-09-26 15:17
I have the same problem: https://github.com/esnet/iperf/issues/333

Might be a buffer problem.

**Comment by bltierney** [comment] 2017-04-06 17:44
unable to replicate. Can you send more details?

**Comment by dahavey** [comment] 2017-05-08 18:42
This problem has been fixed.  iperf should be just as fast and low latency as wget.  Just get the new cygwin1.dll.

Hi I'm from the Windows TCP team and this behavior is because there was a bug in the cygwin1.dll where the TCP buffers (SO_RCVBUF and SO_SNDBUF) were being set manually thus defeating the TCP buffer autotuning algorithm and limiting throughput or inducing excess latencies.  We have been working with the cygwin team (thank you Corrina) and the problem is now fixed.  

I just tested the cygwin1.dll ships with iperf3 is and it has the old slow code.  You can replace your cygwin1.dll with the new version from www.cygwin.com and you will have the full performance of Windows.  

...Daniel

For more information here is a link to our Windows Networking blogpost on the topic: (https://blogs.technet.microsoft.com/networking/2017/05/08/windows-network-performance-suffering-from-bad-buffering/)

**Comment by bmah888** [comment] 2017-05-12 20:53
So nowhere in the original bug report did it mention what platform was being used.  In particular it didn't say "Windows" anywhere.

@dahavey, I very much appreciate your insight into Windows network performance, the point about Cygwin behavior is especially interesting.  I do note that Windows is not one of the platforms that we (ESnet) officially support for iperf3, we also don't distribute executables for Windows (or any other platform for that matter).  I think your comments would be very useful for those third parties who are producing Windows executables of iperf3.

I'm going to close this issue based on a lack of feedback from the original user.

**Closed by bmah888** 2017-05-12 20:53 UTC
Labels: question

**Comment by dahavey** [comment] 2017-05-12 21:01
Yeah, that’s actually who I would like to reach.  Iperf.fr<https://iperf.fr/contact.php> who has the Cygwin dll has a contact link for your github.  That is how I got misdirected.  Thanxs for closing the bug and sorry for the extra email traffic.  I will redirect with iperf.fr.

Thanxs :--)
…Daniel
