### ISSUE TITLE
iperf3: error - unable to receive parameters from client: Address family not supported by protocol

### ISSUE THREAD

**Issue by gideonispeace** [esnet/iperf#1037] opened 2020-08-11 15:40 UTC
This issue is occurring in a redhat 6.10 OS with hardware from HPE servers.

iperf3 version: 3.0.6-1

We are unable to use iperf3 on this server with the error below:
```
iperf3 -s -p 24002 -V
iperf 3.0.6
Linux emshk7slsp03a02 2.6.32-754.27.1.el6.x86_64 #1 SMP Wed Jan 8 05:56:42 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
warning: this system does not seem to support IPv6 - trying IPv4
-----------------------------------------------------------
Server listening on 24002
-----------------------------------------------------------
iperf3: error - unable to receive parameters from client: Address family not supported by protocol
```

```
iperf 3.0.6
Linux emshk7slsp03a02 2.6.32-754.27.1.el6.x86_64 #1 SMP Wed Jan 8 05:56:42 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------
Server listening on 24002
-----------------------------------------------------------
^Ciperf3: interrupt - the server has terminated
```

EDIT: Reformatted program output text for legibility.  --bmah

**Comment by bmah888** [comment] 2020-08-11 20:29
Two comments:  iperf-3.0.6 is extremely old.  You should really consider using a newer version of iperf3 (3.8 is current as of this writing).  There have been a number of bug fixes in the interim, some of which are probably relevant to your use case.

Second, see if giving the `-4` command-line flag to iperf3, to disable attempts to use IPv6, would be helpful.  (Better would be to run in a dual-stack IPv4/IPv6 environment.)

Can you try again with a current build of iperf3 and see if that fixes your problem?

**Comment by gideonispeace** [comment] 2020-08-11 21:06
Thanks bmah888 , i have already tried the -4 option as seen below:

iperf3 -4 -s -p 24002 -V
iperf 3.0.6
Linux emshk7slsp03a02 2.6.32-754.27.1.el6.x86_64 #1 SMP Wed Jan 8 05:56:42 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------
Server listening on 24002
-----------------------------------------------------------
iperf3: error - unable to receive parameters from client:

Please for redhat 6.10 OS which other version of iperf3 is supported ?

**Comment by bmah888** [comment] 2020-08-12 00:26
You should be able to build iperf3 from source on RHEL 6.  I'm not sure if any third-party package repositories would have a package for RedHat 6.

How is the iperf3 client being invoked and what kind of errors are you seeing there?

**Comment by gideonispeace** [comment] 2020-08-12 00:55
This is the error am getting : iperf3: error - unable to receive parameters from client:

**Comment by bmah888** [comment] 2020-08-12 15:51
Sorry...what I meant is that you have given me fairly complete information about how the iperf3 server side is run, but I was asking to see the same kind of information for the client side.  Or are you saying that the server prints that error output even before a client tries to connect to it?  I apologize for not understanding your situation.

**Comment by gideonispeace** [comment] 2020-08-12 15:59
Ohh no need to be sorry for i see you making an effort to help. Thanks again for your help.

Now the situation is like this:
We have never experience this issue before and we are working off just this server and on trying the mentioned command above we got the errors and now we are looking to see how to resolve the error.

We got no client side for this at the moment.

**Comment by bmah888** [comment] 2020-08-12 23:43
About as close as I can get to your environment/configuration is CentOS 6, and I haven't been able to reproduce the problem yet.  Part of the difficulty is it looks like you have an IPv4-only environment and I'm trying to set that up...it seems relevant given some of the errors you've seen.

Anybody else seeing this?

**Comment by gideonispeace** [comment] 2020-08-13 15:14
My environment is redhat 6.10 and not centos 6. No its not IPV4 only because i have also tried the -4 option but got an error still!

There one thing i have witness is that i cannot install any higher version of iperf3 on redhat 6.10 other than the 3.0.6 we currently have.
Thanks,

**Comment by gideonispeace** [comment] 2020-08-14 17:12
Hello bmah888 just to update you on this issue, i just discovered iperf3 runs fine on port 9001 but will only fail with the 24002 port as in the issue above, could you get any better reason why this happens?

**Comment by bmah888** [comment] 2020-08-14 21:01
Wow that's really strange.  Off-hand I can't think of a reason for the iperf3 server to work on 9001 but not 24002.  We run it on non-default ports all the time in our network (although not necessarily 24002 specifically).  Perhaps if you want to dig in to a it a bit more, you could use `lsof` or `netstat` to try to see if there's anything already listening on port 24002?  That might cause the server to fail.

In any case I'm glad you got it to work!

**Comment by bmah888** [comment] 2020-09-09 22:43
I'm going to close this on the basis that it's working, and I can't find any obvious flaw here.  Granted I'm working with much newer code...if you want to try a more recent iperf3 on CentOS 6 you might need to compile it from source.  Please feel free to reopen this if necessary.

**Closed by bmah888** 2020-09-09 22:43 UTC

**Comment by silabs-Roja** [comment] 2022-04-19 08:05
> About as close as I can get to your environment/configuration is CentOS 6, and I haven't been able to reproduce the problem yet. Part of the difficulty is it looks like you have an IPv4-only environment and I'm trying to set that up...it seems relevant given some of the errors you've seen.
> 
> Anybody else seeing this?

Yes, the same error I have seen, at the server-side, an error - iperf3: error - unable to receive parameters from the client, using wifi application at client side. PC to PC there is no issue, with application only seen issue. could you please help us?
