### ISSUE TITLE
Very strange jitter value 

### ISSUE THREAD

**Issue by raszuk** [esnet/iperf#1182] opened 2021-07-08 14:37 UTC
Hi, 

When I run Iperf3 UDP testing (in any direction) to go via specific path I am seeing the below output:

root@fuji:~# iperf3 -s
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 10.160.16.54, port 64065
[  5] local 10.133.5.132 port 5201 connected to 10.160.16.54 port 52287
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec   104 KBytes   852 Kbits/sec  46822443975.381 ms  0/13 (0%)
[  5]   1.00-2.00   sec   120 KBytes   983 Kbits/sec  17783745093.089 ms  0/15 (0%)
[  5]   2.00-3.00   sec   128 KBytes  1.05 Mbits/sec  6332331570.581 ms  0/16 (0%)
[  5]   3.00-4.00   sec   128 KBytes  1.05 Mbits/sec  2254779458.383 ms  0/16 (0%)
[  5]   4.00-5.00   sec   128 KBytes  1.05 Mbits/sec  802868635.583 ms  0/16 (0%)
[  5]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  285880752.080 ms  0/16 (0%)
[  5]   6.00-7.00   sec   128 KBytes  1.05 Mbits/sec  101794740.820 ms  0/16 (0%)
[  5]   7.00-8.00   sec   128 KBytes  1.05 Mbits/sec  36246474.556 ms  0/16 (0%)
[  5]   8.00-9.00   sec   128 KBytes  1.05 Mbits/sec  12906432.687 ms  0/16 (0%)
[  5]   9.00-10.00  sec   128 KBytes  1.05 Mbits/sec  4595647.335 ms  0/16 (0%)
[  5]  10.00-11.00  sec   128 KBytes  1.05 Mbits/sec  1636391.733 ms  0/16 (0%)
[  5]  11.00-12.00  sec   128 KBytes  1.05 Mbits/sec  582677.244 ms  0/16 (0%)
[  5]  12.00-13.00  sec   128 KBytes  1.05 Mbits/sec  207476.898 ms  0/16 (0%)
[  5]  13.00-14.00  sec   128 KBytes  1.05 Mbits/sec  73878.125 ms  0/16 (0%)
[  5]  14.00-15.00  sec   128 KBytes  1.05 Mbits/sec  26306.747 ms  0/16 (0%)
[  5]  15.00-16.00  sec   128 KBytes  1.05 Mbits/sec  9367.741 ms  0/16 (0%)
[  5]  16.00-17.00  sec   128 KBytes  1.05 Mbits/sec  3336.365 ms  0/16 (0%)
[  5]  17.00-18.00  sec   128 KBytes  1.05 Mbits/sec  1188.556 ms  0/16 (0%)
[  5]  18.00-19.00  sec   128 KBytes  1.05 Mbits/sec  423.780 ms  0/16 (0%)
[  5]  19.00-20.00  sec   128 KBytes  1.05 Mbits/sec  151.539 ms  0/16 (0%)
[  5]  20.00-21.00  sec   128 KBytes  1.05 Mbits/sec  54.662 ms  0/16 (0%)
[  5]  21.00-22.00  sec   136 KBytes  1.11 Mbits/sec  18.977 ms  0/17 (0%)
[  5]  22.00-23.00  sec   120 KBytes   983 Kbits/sec  8.196 ms  0/15 (0%)
[  5]  23.00-24.00  sec   128 KBytes  1.05 Mbits/sec  3.342 ms  0/16 (0%)
[  5]  24.00-25.00  sec   128 KBytes  1.05 Mbits/sec  1.882 ms  0/16 (0%)
[  5]  25.00-26.00  sec   128 KBytes  1.05 Mbits/sec  1.416 ms  0/16 (0%)
[  5]  26.00-27.00  sec   128 KBytes  1.05 Mbits/sec  1.147 ms  0/16 (0%)
[  5]  27.00-28.00  sec   128 KBytes  1.05 Mbits/sec  0.977 ms  0/16 (0%)
[  5]  28.00-29.00  sec   128 KBytes  1.05 Mbits/sec  1.109 ms  0/16 (0%)
[  5]  29.00-30.00  sec   128 KBytes  1.05 Mbits/sec  0.775 ms  0/16 (0%)
[  5]  30.00-31.00  sec   128 KBytes  1.05 Mbits/sec  1.018 ms  0/16 (0%)
[  5]  31.00-32.00  sec   128 KBytes  1.05 Mbits/sec  1.338 ms  0/16 (0%)
[  5]  32.00-33.00  sec   128 KBytes  1.05 Mbits/sec  1.301 ms  0/16 (0%)
[  5]  32.00-33.00  sec   128 KBytes  1.05 Mbits/sec  1.301 ms  0/16 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[SUM]  0.0-33.0 sec  2 datagrams received out-of-order
[  5]   0.00-33.00  sec  4.11 MBytes  1.04 Mbits/sec  1.244 ms  0/526 (0%)  receiver
iperf3: the client has terminated

Obviously numerically the jitter reported is wrong - I am reporting is as bug. 

But what I am really more curious is what caching device on the path may have been causing such output. 

Note that if I go between the same src and dst over different network path the results are fine: 

-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 10.244.10.114, port 55446
[  5] local 10.244.10.211 port 5201 connected to 10.244.10.114 port 52158
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  96.0 KBytes   786 Kbits/sec  3.108 ms  0/12 (0%)
[  5]   1.00-2.00   sec   128 KBytes  1.05 Mbits/sec  2.391 ms  0/16 (0%)
[  5]   2.00-3.00   sec   128 KBytes  1.05 Mbits/sec  1.617 ms  0/16 (0%)
[  5]   3.00-4.00   sec   128 KBytes  1.05 Mbits/sec  1.168 ms  0/16 (0%)
[  5]   4.00-5.00   sec   128 KBytes  1.05 Mbits/sec  1.052 ms  0/16 (0%)
[  5]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  0.887 ms  0/16 (0%)
[  5]   6.00-7.00   sec   128 KBytes  1.05 Mbits/sec  0.914 ms  0/16 (0%)
[  5]   7.00-8.00   sec   128 KBytes  1.05 Mbits/sec  0.917 ms  0/16 (0%)
[  5]   8.00-9.00   sec   128 KBytes  1.05 Mbits/sec  0.870 ms  0/16 (0%)
[  5]   9.00-10.00  sec   128 KBytes  1.05 Mbits/sec  1.053 ms  0/16 (0%)
[  5]  10.00-11.00  sec   128 KBytes  1.05 Mbits/sec  0.819 ms  0/16 (0%)
[  5]  11.00-12.00  sec   128 KBytes  1.05 Mbits/sec  0.728 ms  0/16 (0%)
[  5]  12.00-13.00  sec   128 KBytes  1.05 Mbits/sec  0.876 ms  0/16 (0%)
[  5]  13.00-14.00  sec   128 KBytes  1.05 Mbits/sec  0.903 ms  0/16 (0%)
[  5]  14.00-15.00  sec   128 KBytes  1.05 Mbits/sec  1.727 ms  0/16 (0%)
[  5]  15.00-16.00  sec   128 KBytes  1.05 Mbits/sec  1.146 ms  0/16 (0%)
[  5]  16.00-17.00  sec   128 KBytes  1.05 Mbits/sec  0.684 ms  0/16 (0%)
[  5]  17.00-18.00  sec   128 KBytes  1.05 Mbits/sec  1.344 ms  0/16 (0%)
[  5]  17.00-18.00  sec   128 KBytes  1.05 Mbits/sec  1.344 ms  0/16 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-18.00  sec  0.00 Bytes  0.00 bits/sec  1.233 ms  0/287 (0%)
iperf3: the client has terminated

**Comment by davidBar-On** [comment] 2021-07-09 09:21
Are you using a version older than 3.8 (i.e. 3.7, 3.1.3)?  If yes, then probably the jitter issue is already solved by PR #990.  If this is the case, then the client is probably sending about 16 UDP packets per second with size of about 64KB each.

(The above does not explain why the there is a difference between the different routs.  You will need to share more data to evaluate that: the client command, how is the rout set, maybe the relevant network architecture, etc.)

**Comment by raszuk** [comment] 2021-07-09 10:56
I see the same behavior using ubuntu client iperf 3.9 (cJSON 1.7.13) as well as windows 3.1.3 (is there some newer build for windows) ? Servers are 3.0.7 and 3.7-3.  Both are latest as far as apt install says for the platforms. 

Do I need to upgrade both server and client or just clients ? Btw I have seen it in both directions however upgrading the servers is a bit harder in my env. 

My server cmd is -s -i 1 -t 0, client -c <ip> -u -t 0 

I am connecting to the servers over IPSec VPN path via Azure. (Btw - the same happens also when I use ZeroTier).  The only difference here is that the return path. 

I run some debug from testing using same windows client and I see that on the host working fine UDP comes clean: 

03:48:54.076125 IP 10.160.16.200.55321 > 10.133.5.201.4545: UDP, length 8192
03:48:54.076139 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.076141 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.076143 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.076145 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.076147 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.078475 IP 10.160.16.200.55321 > 10.133.5.201.4545: UDP, length 8192
03:48:54.078490 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.078492 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.078494 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.078495 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.078497 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.167060 IP 10.160.16.200.55321 > 10.133.5.201.4545: UDP, length 8192
03:48:54.167078 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.167080 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.167082 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.167084 IP 10.160.16.200 > 10.133.5.201: udp
03:48:54.167086 IP 10.160.16.200 > 10.133.5.201: udp

But on the one with messed out output I see lots of bad length errors: 

03:52:44.523422 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:44.631218 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:44.716105 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:44.720382 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:44.832811 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:44.923400 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:44.924415 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.035945 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.039105 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.129586 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.223081 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.225827 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.276370 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 290
03:52:45.327337 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.329243 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.422262 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.512394 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 78
03:52:45.537858 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.540739 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.627733 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.720778 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.725193 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.828605 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.917896 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:45.924331 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.032801 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.035350 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.129928 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.232494 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.235386 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.276374 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 210
03:52:46.331325 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.416827 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.420467 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.513179 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 78
03:52:46.527414 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.529682 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.622537 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.733807 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.735501 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.827792 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.940208 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:46.942867 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:47.027959 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:47.030093 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:47.117286 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368

Server is also trying to tell client something :) 

03:52:48.427154 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:48.428977 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:48.494161 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 78
03:52:48.526682 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:48.529234 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:48.630859 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:48.726448 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:48.728782 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368
03:52:48.829224 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 466
03:52:48.829313 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 274
03:52:49.017935 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 78
03:53:04.968408 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 28
03:53:05.158000 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 37
03:53:20.120553 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 28
03:53:20.306900 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 37
03:53:25.094353 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 130
03:53:25.094712 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 78
03:53:29.080382 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 117
03:53:29.080527 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 97
03:53:29.748238 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 66
03:53:29.748550 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 66
03:53:45.049086 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 28
03:53:45.049257 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 37
03:54:00.477930 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 28
03:54:00.663544 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 37
03:54:15.632441 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 28
03:54:15.819955 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 37
03:54:26.109047 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 315
03:54:26.109047 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 130
03:54:26.120353 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 78
03:54:30.747751 IP 10.160.16.200.20958 > 10.133.5.132.32450: UDP, length 66
03:54:30.747899 IP 10.133.5.132.32450 > 10.160.16.200.20958: UDP, length 97

Many thx,
R.

**Comment by davidBar-On** [comment] 2021-07-09 13:24
> Do I need to upgrade both server and client or just clients ?

Jitter is measured by the receiving size, the server in your case.  With `-R` it will be measured by the client.

> But on the one with messed out output I see lots of bad length errors:
03:52:44.523422 IP 10.160.16.200.58787 > 10.133.5.132.4545: UDP, bad length 8192 > 1368

It seems that the MTU of the "bad" rout is 1368 and for some reason the (probably) 64KB UDP packets are fragmented to just 8KB packets.  **Try using the client with `-l 1300`.**  If the main problem is the packets size that will solve the issue.

The root cause is probably because a problem in receiving the first packet.  See issue #1123 for one possible explanation.

> Server is also trying to tell client something :)

These are probably the control messages and statistics exchanged between the client end the server.

> is there some newer build for windows

There is a site that distributes new iperf3 executable for Windows. This is not an iperf3 official site it seem to be reliable: [https://files.budman.pw/](https://files.budman.pw/) or [https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/](https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/) (in both download is done from the same site).

**Comment by bmah888** [comment] 2022-02-14 21:21
Believed fixed by #1260

**Closed by bmah888** 2022-02-14 21:21 UTC
