### ISSUE TITLE
iperf3 does not support -B option on windows and Linux

### ISSUE THREAD

**Issue by akrambaig41** [esnet/iperf#449] opened 2016-08-11 21:41 UTC
iperf3 does not support -B option on windows and Linux
Tried on version 3.1.3 and later

Best,
Akram

**Comment by wangyoucao577** [comment] 2016-08-12 01:32
I use the -B option with iperf3 for many times on Linux, and it works well. But notice that I use it to bind ip address of indicated interface instead of interface itself. 
Actually I found that iperf2 said that they can support this option but not work on my machine, so that I switch to iperf3 and it works well. 

My test enviromment: 
iperf 3.0.11, 
Linux kernel 2.6.37, 3.17.0.

**Comment by bam80** [comment] 2016-08-12 16:30
I've opened https://github.com/esnet/iperf/issues/450 related to this

**Comment by bmah888** [comment] 2016-08-12 21:43
@akrambaig41 :  Need more information on what's not working for you.  I did a quick test on a CentOS 6 VM and ```-B``` appears to work correctly for both the client and server sides.  What are your command line arguments and outputs / errors?

**Comment by akrambaig41** [comment] 2016-08-12 21:57
1) Ubuntu 12.04.3 LTS
   with -B option iperf3 cmd is getting executed but it does not show any binding info and also NO traffic from client, but when I use regular iperf its working fine.

2) Windows Server 2012 R2 64bit
     C:>iperf3 -s -B 224.0.0.1 
      iperf3: error - unable to start listener for connections: Cannot assign requested address
      iperf3: exiting

**Comment by bmah888** [comment] 2016-08-12 22:02
On the Ubuntu case, you still didn't give a complete command line or output.  Kind of hard to help without more complete information.

In the Windows case, you're trying to bind to a multicast address.  This isn't supported.

**Comment by akrambaig41** [comment] 2016-08-12 22:05
its the same cmd, where im trying to bind it to multicast address.

**Comment by bmah888** [comment] 2016-08-12 22:06
OK, so then really the problem is that iperf3 doesn't currently support multicast.

This is really a duplicate of #27.

**Closed by bmah888** 2016-08-12 22:06 UTC
Labels: duplicate

**Comment by bmah888** [comment] 2016-08-12 22:18
Right now there are no plans to support multicast.  Speaking for myself only, the main issue is that implementing this feature would take a non-trivial amount of effort (mainly due to the fact that there's a unicast control channel between client and server, and that figuring out how to adapt that to a testing scenario with a single sender and multiple clients is...well...non-trivial).  ESnet supports only a very limited amount of development and maintenance time for iperf3, and implementing multicast support is too big of a project to take on.

The chance of this feature showing up in a release would be somewhat higher if someone in the community were to submit a source code patch that implements it.
