### ISSUE TITLE
iperf3 retransmits reporting on FreeBSD

### ISSUE THREAD

**Issue by he32** [esnet/iperf#243] opened 2015-02-08 19:00 UTC
Hi,

while porting the TCP_INFO getsockopt() feature to NetBSD from
FreeBSD, I noticed that iperf3 has retransmit reporting turned off
for FreeBSD because "it does not work".  Looking at the kernel code
for FreeBSD's TCP_INFO, it looks like they report retransmits via
another field in the tcp_info struct, so this change is probably appropriate:

@@ -82,8 +83,9 @@ has_tcpinfo_retransmits(void)
     return 1;
 #else
 #if defined(__FreeBSD__) && __FreeBSD_version >= 600000
-    /* return 1; */
-    return 0;  /* FreeBSD retransmit reporting doesn't actually work yet */
+    return 1; /* Should work now */
@@ -114,12 +118,30 @@ get_total_retransmits(struct iperf_inter
 {
 #if defined(linux) && defined(TCP_MD5SIG)
     return irp->tcpInfo.tcpi_total_retrans;
-#else
-#if defined(__FreeBSD__) && __FreeBSD_version >= 600000
-    return irp->tcpInfo.__tcpi_retransmits;
+#elif defined(__FreeBSD__) && __FreeBSD_version >= 600000
+    return irp->tcpInfo.tcpi_snd_rexmitpack;

(The line numbers are probably off, since I have NetBSD changes
in there too.)

Regards,

- Håvard

**Comment by he32** [comment] 2015-02-08 19:00
(oh, well, the diff got mangled by the markdown, but I think the gist is still understandable)

**Comment by bmah888** [comment] 2015-05-08 22:40
This was previously fixed by the pull request #243.  Closing this as a duplicate of the pull request.

**Closed by bmah888** 2015-05-08 22:40 UTC
Labels: duplicate
