### ISSUE TITLE
Please accept `--port 0` as a valid argument

### ISSUE THREAD

**Issue by MrMino** [esnet/iperf#931] opened 2019-11-15 13:36 UTC
# Context
`--port 0`, which makes iperf bind to an unused, ephemeral port, has been deemed to be an unacceptable use case, a bug (#884). Afterwards, code has been added to defend against it (#885).

Previously, iperf could start with `--port 0`, it just didn't show the used port correctly.

Original issue (#831) called for adding additional code from #832, that made iperf print the actually used port instead of the value taken from `argv`. This pull request has been declined.

# The issue
I would like to kindly request that this action be reconsidered. There are valid uses for `--port 0`, especially in test automation, where finding a free port isn't easy and doing it incorrectly leads to unnecessary failures. #832 is a good piece of code that enables additional uses for iperf. I, and a few of my colleagues fail to see a downside to it, hence this appeal.

Using `0` as a port number is idiomatic to Linux users, and is a good shorthand for when you don't actually care.
It avoids port reuse failures in environments with heavy port usage. In my daily work I have to deal with LTE/5G EPC hosts, where it's normal to see hundreds of runs of iperf from different automated testcases.
It makes it possible to create scripts where the user doesn't have to give a port.
It makes starting up the server simpler, as you don't have to worry about the port (well, it would, if #832 was merged).

# Proposed solution
It should not be possible to use a negative port number, so let's make #885 stay.
Please consider merging #832. Additionally, please consider merging #930, which makes the usage of `--port 0` possible.

**Comment by bmah888** [comment] 2019-11-27 18:39
I acknowledge seeing this plus your pull request #930.  I'm not totally convinced, but I promise to actually read your justification and seriously think about it.

**Comment by bmah888** [comment] 2020-01-02 19:40
If I understand this correctly, the use case here is that you want to start up an iperf3 server, but you don't care what TCP port it binds to.  So how does an iperf3 client find the server?  Right now the only way that any process (aside from the server process itself) knows that TCP port number would be if the server communicates that somehow.

You mentioned that `--port 0` is idiomatic for Linux users.  I would agree with you for the cases where you have a client making a connection to a server at a well-known address/port and you don't care what port the client uses on its case.  That's the prototypical case for binding to an ephemeral port.  The problem is that if you have a service that needs to be found, you don't want to use an ephemeral port because no client will know the correct port number.  I've been around UNIX systems since 1987 and I don't think I've ever heard of someone wanting to do this before.

It sounds like in the testing scenario you are describing, you need the iperf3 server to print the ephemeral port number to stdout so that something can screen-scrape the number and use that to tell the client where to look.  Note this isn't going to work with `--json`.  Also it's kind of brittle in that if we ever change the human-readable output format (this does happen occasionally) it's possible to break your testing framework (unintentionally, of course).

You mentioned that finding a free port isn't easy...I suppose that'd be true if you had many iperf3 processes independently trying to decide on a port number, but maybe a better approach would be to have something "hand out" port numbers to the iperf3 server processes?

The way iperf3 is called in the perfSONAR context (which is the use case that iperf3 is designed for) is that there's a coordinating process (pScheduler) that sets up the client and server parameters for a test and instantiates both of them with the correct arguments, including the port numbers.

In a way I guess I'm trying to discourage you from taking the approach you are (at least based on my guesses about how iperf3 is being used), but it probably wouldn't be the end of the world from my perspective if we did what you asked.  The main downside I can see from a user perspective is that `--port 0` might get them confused if they don't know what they're doing.  Perhaps that's not a huge risk.

Am I missing something?

**Comment by MrMino** [comment] 2020-01-03 10:33
> If I understand this correctly, the use case here is that you want to start up an iperf3 server, but you don't care what TCP port it binds to. So how does an iperf3 client find the server?

That's why I requested #832 to be merged. It would make it possible to find out which port is actually used.

> It sounds like in the testing scenario you are describing, you need the iperf3 server to print the ephemeral port number to stdout so that something can screen-scrape the number and use that to tell the client where to look. Note this isn't going to work with --json. Also it's kind of brittle in that if we ever change the human-readable output format (this does happen occasionally) it's possible to break your testing framework (unintentionally, of course).

Fully agree. It's just that I actually gave more weight to the fact that I don't have to do the "port finding", which at the time felt brittler for me than screen scraping.

> but maybe a better approach would be to have something "hand out" port numbers to the iperf3 server processes?

In general case, yes. For my particular use case however, there's no way to do that because of nuances of the testing environment / mobile networks testing. I just cannot impose such service over every testcase that is running in the lab. But yes, if I could, that's what I would do.

> The way iperf3 is called in the perfSONAR context (which is the use case that iperf3 is designed for) 

Seems like the fame of iperf outruns perfSONAR, cause I've never heard of it. Looks like it might be useful for me, thank you for pointing it out :).

> In a way I guess I'm trying to discourage you from taking the approach you are

After you've brought `--json` to my attention I feel like I'd rather have the machine-readable output, than a fire-proof way of finding a free port.

Anyway, my appetite for this feature got significantly extinguished now. It still looks to me that the pros outweigh the cons, but I can see how such feature wouldn't fit into the development philosophy of the project.

**Comment by bmah888** [comment] 2020-01-03 21:12
OK, sounds good.  FWIW it was actually fun thinking about and discussing this.  Going to close this and #930 for now, thanks for the PR and discussion!

**Closed by bmah888** 2020-01-03 21:12 UTC
Labels: enhancement
