### ISSUE TITLE
Reverse mode using --omit has incorrect values at end of test

### ISSUE THREAD

**Issue by ebilleter** [esnet/iperf#443] opened 2016-07-22 00:48 UTC
Observed with both 
iperf 3.1.3 installed from iperf3_3.1.3-1_arm64.deb
iperf 3.0.11 installed from iperf3-3.0.11-1.el6.x86_64

The numbers reported at the end of the test do not make sense when compared to each individual time interval.

i.e.  each interval reported 924 (or less) but the value at the end (sender/receiver) value is 950.

With larger values for -O the larger the drift becomes between the reported intervals and the sender/receiver value at the end. You can even have sender/receiver values reported at the end which exceed the available bandwidth of the line.  For simplicity I used -t of 1, however the behavior is present with larger testing periods as well.  

I did not observe this when performing this **without** -R 
```
for i in `seq 1 60`; 
do 
echo Omit $i

iperf3 -c xx.xx.xx.xx  -R -P10 -O$i -t 1 | grep SUM
echo " "
echo " "
done
```

 -R (all omitted values were <= 925)
```
[SUM]  53.00-54.00  sec   110 MBytes   924 Mbits/sec                  (omitted)
[SUM]  54.00-55.00  sec   110 MBytes   924 Mbits/sec                  (omitted)
[SUM]  55.00-56.00  sec   110 MBytes   924 Mbits/sec                  (omitted)
[SUM]  56.00-57.00  sec   110 MBytes   925 Mbits/sec                  (omitted)
[SUM]  57.00-58.00  sec   110 MBytes   924 Mbits/sec                  (omitted)
[SUM]  58.00-59.00  sec   110 MBytes   925 Mbits/sec                  (omitted)
[SUM]   0.00-1.00   sec   110 MBytes   924 Mbits/sec
[SUM]   0.00-1.00   sec   114 MBytes   954 Mbits/sec    0             sender
[SUM]   0.00-1.00   sec   139 MBytes  1.17 Gbits/sec                  receiver
```
 -R (all omitted values were  <= 101 )
```
[SUM]  56.00-57.00  sec  11.9 MBytes  99.6 Mbits/sec                  (omitted)
[SUM]  57.00-58.00  sec  11.9 MBytes  99.6 Mbits/sec                  (omitted)
[SUM]  58.00-59.00  sec  12.0 MBytes   101 Mbits/sec                  (omitted)
[SUM]  59.00-60.00  sec  11.8 MBytes  98.6 Mbits/sec                  (omitted)
[SUM]   0.00-1.00   sec  11.2 MBytes  94.4 Mbits/sec
[SUM]   0.00-1.00   sec  12.5 MBytes   105 Mbits/sec    0             sender
[SUM]   0.00-1.00   sec  12.5 MBytes   105 Mbits/sec                  receiver
```
This is what I would expect.. and is what you get when not in Reverse -R (omitted values not included.)
```  
[SUM]   0.00-1.00   sec  11.2 MBytes  94.4 Mbits/sec    0
[SUM]   0.00-1.00   sec  11.2 MBytes  94.4 Mbits/sec    0             sender
[SUM]   0.00-1.00   sec  11.2 MBytes  94.4 Mbits/sec                  receiver
```
EDIT:  Reformatting for increased legibility.  --bmah

**Comment by bmah888** [comment] 2017-04-14 17:34
Assign to @bltierney to try to reproduce the problem.  If it can be reproduced, then give to @bmah888.

**Comment by bltierney** [comment] 2017-04-28 16:44
I think this is related to #236 , and seems to still be a problem. See that issue for more info.

**Comment by bmah888** [comment] 2017-05-11 21:26
I'm not seeing any signs of this problem on current master code (the significant features of the test case seem to be reverse mode, UDP, multi-stream, omit mode, and that the end-of-test bitrates reported are not consistent with the per-interval summaries).  Note that we did just make a number of reporting fixes in recent iperf3 code (not released yet, but intended to be a part of an upcoming iperf 3.2 release).
```
[bmah@antg-staging iperf]$ src/iperf3 --client antg-dev.es.net --port 5202 -4 --udp --reverse -P10 -t 1 -O 5 | grep SUM
[SUM]   0.00-1.00   sec  1.28 MBytes  10.8 Mbits/sec  0.118 ms  0/930 (0%)  (omitted)
[SUM]   1.00-2.00   sec  1.26 MBytes  10.5 Mbits/sec  0.082 ms  0/910 (0%)  (omitted)
[SUM]   2.00-3.00   sec  1.24 MBytes  10.4 Mbits/sec  0.166 ms  0/900 (0%)  (omitted)
[SUM]   3.00-4.00   sec  1.26 MBytes  10.5 Mbits/sec  0.228 ms  0/910 (0%)  (omitted)
[SUM]   4.00-5.00   sec  1.24 MBytes  10.4 Mbits/sec  0.101 ms  0/900 (0%)  (omitted)
[SUM]   0.00-1.00   sec  1.26 MBytes  10.5 Mbits/sec  0.134 ms  0/910 (0%)
[SUM]   0.00-1.02   sec  1.28 MBytes  10.5 Mbits/sec  0.000 ms  0/910 (0%)  sender
[SUM]   0.00-1.00   sec  1.26 MBytes  10.5 Mbits/sec  0.134 ms  0/910 (0%)  receiver
```

**Comment by bmah888** [comment] 2017-05-12 17:21
After some discussion we've tentatively concluded that this bug has been fixed by recent code changes dealing with reporting.  Closing this issue, please feel free to re-open if we haven't really fixed it.

**Closed by bmah888** 2017-05-12 17:21 UTC
Labels: bug
