### ISSUE TITLE
Add new option to allow multiple clients

### ISSUE THREAD

**Issue by Thalwander** [esnet/iperf#327] opened 2015-11-12 19:37 UTC
**Enhancement**

_Add a new server option to allow multiple client connections._

If the iPerf server is started with this option, the server will accept multiple parallel client connections. The clients can run tests in parallel.

If the iPerf server is started without this option, it will work exactly as today (only one client at a time will be accepted).

**Why**

We use iPerf to measure the bandwidth of mobile networks. In our test environment the iPerf client runs on a Windows PC with a mobile broadband dongle or a tethered smartphone with low bandwidth (< 100 Mbit/s). The iPerf server runs on a Linux server which sits in a 10 Gbit/s network.

To run a test, a tester has to start both the iPerf server on the remote Linux server, and the iPerf client on the local Windows PC. If the iPerf server accepted multiple clients, we could run the server as a daemon on the Linux server, and the tester would just need to start the client. This would mean a great simplification to our test environment. Since the server sits in a 10 Gbit/s network it can handle lots of clients without interference.

Starting several iPerf server processes on different ports on the Linux server is an option, but is too impractical.

**Comments**

This is the same enhancement as [Issue 130](https://code.google.com/p/iperf/issues/detail?id=130), which was rejected. However, that issue did not describe why this feature is needed. I hope I have made it clear here.

**Comment by bmah888** [comment] 2015-11-18 22:17
I'll leave this bug open, but to reiterate a comment I made in #130, multiple client support isn't a part of the iperf3 design.  I'm not saying it's not a valid use...I can perfectly well see that it would be useful.  It's not something that we would use at ESnet.

iperf3 was designed to be relatively simple to maintain (particularly compared to its predecessor).  We could discuss whether it succeeded in that goal or not, but there are a number of useful features that would add significant complexity to iperf3's design and implementation.  Multiple client support is one of those.

Given the current development model (basically 5% of one developer's time), this is unlikely to be implemented anytime soon.  If someone in the community were to step up and implement the proposed feature, there's a somewhat more likely chance of seeing this integrated into the codebase.

**Comment by Thalwander** [comment] 2015-11-19 21:27
Thanks for your comment! I will implement this and submit a patch. Then you can decide if you find it to add too much complexity or if you want to integrate it into the code base.

**Comment by Fruglemonkey** [comment] 2016-01-06 00:44
@Thalwander , any progress? This is functionality that I could make use of in my research/testing.

**Comment by TheRealDJ** [comment] 2016-02-15 20:09
You could do what I did and spin up multiple iperf3 server processes on multiple ports. Then on the client side, if it gets a "server busy" message back from the server, try the next port.

**Comment by dikshit1805** [comment] 2016-11-15 15:33
@Thalwander Any progress on the support for multiple clients ?
@bmah888 I completely understand why you have restricted to only connection at a time. But is it possible to queue the other clients which request the connection to the server. ?
Can you implement this support to queue the connection ? it will be very useful when your trying to automate iperf3 testing via a framework or a simple script.  
I feel that this feature support requires very minimum resources but it can surely help a lot of people who is trying to automatize the testing using frameworks like Jenkins, caliper etc.

**Comment by bmah888** [comment] 2016-11-16 23:11
Queueing connections seems like it'd be a little bit easier.  I tried basically not listening for new connections if we already have a control connection and we aren't accepting data streams.  This prevented a new client from dying immediately, but the server closes its listening socket after every test (and re-opens it again), thus causing the client to fail at the end of the test.

In the perfSONAR use case, we rely on bwctl (or the new pScheduler) to coordinate instances of the iperf3 server and client.  Note that one of its objectives is specifically to not have multiple tests running at once, so it doesn't really solve the original problem.

```
	/*
	 * If we already have a control socket, then don't try doing an accept
	 * of a new connection.  Instead let the control connection attempt
	 * queue until after the current test is done.
	 */
	if (test->ctrl_sck > -1 && test->state != CREATE_STREAMS) {
	    FD_CLR(test->listener, &read_set);
	}

```

**Comment by bltierney** [comment] 2017-03-30 18:03
not designed to do this. closing

**Closed by bltierney** 2017-03-30 18:03 UTC
Labels: enhancement

**Comment by 2048-Bit** [comment] 2017-07-10 13:01
Just because it's not designed to do this doesn't mean it can't be.

**Comment by ktorn** [comment] 2017-07-17 13:31
My use case is to have 2 or 3 people concurrently testing ethernet ports against the same iperf server without getting in each other's way. Connection queuing would be perfect as it would avoid people randomly retrying connections.

Since this functionality is not in place I'm working on my own queueing server. On the client-side I'll wrap iperf3 in a script that acquires and releases tokens from the queueing server.

**Comment by bltierney** [comment] 2017-07-17 14:51
why not just use iperf2? I think iperf2 supports multiple clients...

also see: 
https://fasterdata.es.net/performance-testing/network-troubleshooting-tools/throughput-tool-comparision/

**Comment by bmah888** [comment] 2017-07-17 17:27
@2048-Bit :  Regardless of what iperf3 was or was not designed to do, there are currently no plans to support multiple client connections.  That's why this issue is "closed".  The source code for iperf3 is freely available for anyone who wants to try implementing it themselves.

@ktorn:  You might also want to take a look at pScheduler, part of the perfSONAR toolkit.  Connection queueing is exactly what pScheduler was designed for (and it directly supports iperf3).

**Comment by Luo-Liang** [comment] 2018-03-29 02:36
In desperate need of this!

**Comment by rfjakob** [comment] 2018-03-29 18:04
@Luo-Liang Use iperf2. Like iperf3, iperf2 is still being actively maintained, so there is no reason not to. Check out https://github.com/esnet/iperf/blob/master/docs/faq.rst#iperf3-faq for the relation between iperf2 and iperf3. Also, not that the Debian and Fedora package for iperf2 is just called `iperf`.

**Comment by hamzash9500** [comment] 2020-11-06 07:48
any update about this requirement

**Comment by lasithwaruna** [comment] 2021-10-01 17:49
quick fix is implemented (TCP Only)

https://github.com/lasithwaruna/iperf
