### ISSUE TITLE
Negative Cwnd values shown

### ISSUE THREAD

**Issue by jlpetz** [esnet/iperf#338] opened 2016-01-05 03:47 UTC
I was doing perf testing from a FreeBSD 11(CURRENT) client

```
root@ip-172-31-4-176:~ # iperf3 -v
iperf 3.1.1
FreeBSD ip-172-31-4-176 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r293137M: Mon Jan  4 11:24:40 UTC 2016     root@ip-172-31-8-215:/usr/obj/usr/src/sys/GENERIC amd64
Optional features available: CPU affinity setting, SCTP, TCP congestion algorithm setting, sendfile / zerocopy
```

To a Linux server

```
[ec2-user@ip-172-31-13-127 ~]$ iperf3 -v
iperf 3.0.11
Linux ip-172-31-13-127 4.1.13-19.30.amzn1.x86_64 #1 SMP Fri Dec 11 03:42:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

The purpose of the test was to shake test support for EC2 enhanced networking
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html
and a 9001 MTU.

When testing with a 9001 MTU I found that the client number for 'Cwnd' turn negative at times. I imagine there is an overflow in the code for large Cwnd numbers making them appear negative?

Example

```
# iperf3 -c 172.31.13.127 -t 120 -i 30 -P 4
Connecting to host 172.31.13.127, port 5201
[  4] local 172.31.4.176 port 20103 connected to 172.31.13.127 port 5201
[  6] local 172.31.4.176 port 12734 connected to 172.31.13.127 port 5201
[  8] local 172.31.4.176 port 34893 connected to 172.31.13.127 port 5201
[ 10] local 172.31.4.176 port 65052 connected to 172.31.13.127 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-30.00  sec   869 MBytes   243 Mbits/sec  114   -1652175463.00 Bytes
[  6]   0.00-30.00  sec   296 MBytes  82.9 Mbits/sec  175   1.12 GBytes
[  8]   0.00-30.00  sec   305 MBytes  85.3 Mbits/sec  198   1.12 GBytes
[ 10]   0.00-30.00  sec   272 MBytes  75.9 Mbits/sec  253    916 MBytes
[SUM]   0.00-30.00  sec  1.70 GBytes   487 Mbits/sec  740
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]  30.00-60.00  sec   799 MBytes   223 Mbits/sec  108    334 MBytes
[  6]  30.00-60.00  sec   279 MBytes  77.9 Mbits/sec  164   1.34 GBytes
[  8]  30.00-60.00  sec   275 MBytes  77.0 Mbits/sec  175   1.57 GBytes
[ 10]  30.00-60.00  sec   244 MBytes  68.3 Mbits/sec  257   1.57 GBytes
[SUM]  30.00-60.00  sec  1.56 GBytes   447 Mbits/sec  704
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]  60.00-90.00  sec   799 MBytes   223 Mbits/sec  110   -450906448.00 Bytes
[  6]  60.00-90.00  sec   248 MBytes  69.4 Mbits/sec  232   1.49 GBytes
[  8]  60.00-90.00  sec   265 MBytes  74.1 Mbits/sec  202   1.27 GBytes
[ 10]  60.00-90.00  sec   285 MBytes  79.8 Mbits/sec  162   1.49 GBytes
[SUM]  60.00-90.00  sec  1.56 GBytes   447 Mbits/sec  706
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]  90.00-120.00 sec   799 MBytes   223 Mbits/sec  110   -1411921660.00 Bytes
[  6]  90.00-120.00 sec   284 MBytes  79.5 Mbits/sec  158   1.27 GBytes
[  8]  90.00-120.00 sec   265 MBytes  74.0 Mbits/sec  197   1.49 GBytes
[ 10]  90.00-120.00 sec   249 MBytes  69.7 Mbits/sec  250   1.19 GBytes
[SUM]  90.00-120.00 sec  1.56 GBytes   447 Mbits/sec  715
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-120.00 sec  3.19 GBytes   228 Mbits/sec  442             sender
[  4]   0.00-120.00 sec  3.19 GBytes   228 Mbits/sec                  receiver
[  6]   0.00-120.00 sec  1.08 GBytes  77.4 Mbits/sec  729             sender
[  6]   0.00-120.00 sec  1.08 GBytes  77.4 Mbits/sec                  receiver
[  8]   0.00-120.00 sec  1.08 GBytes  77.6 Mbits/sec  772             sender
[  8]   0.00-120.00 sec  1.08 GBytes  77.6 Mbits/sec                  receiver
[ 10]   0.00-120.00 sec  1.03 GBytes  73.4 Mbits/sec  922             sender
[ 10]   0.00-120.00 sec  1.03 GBytes  73.4 Mbits/sec                  receiver
[SUM]   0.00-120.00 sec  6.38 GBytes   457 Mbits/sec  2865             sender
[SUM]   0.00-120.00 sec  6.38 GBytes   457 Mbits/sec                  receiver
```

**Comment by bmah888** [comment] 2017-03-30 20:44
I believe #475 is the same issue.  We already triaged that bug so (rather arbitrarily) mark this bug as a duplicate of that newer bug.

**Closed by bmah888** 2017-03-30 20:44 UTC
Labels: duplicate
