### ISSUE TITLE
Reverse mode and file parameter results in breakpoint trap

### ISSUE THREAD

**Issue by fleskalebas** [esnet/iperf#789] opened 2018-09-07 14:14 UTC
# Context
iperf3 reverse network test with file parameter over TCP fails over IPv4 and IPv6
UDP works fine, without -F works fine too. Only TCP + -F results in Trace/breakpoint trap on the server
OpenWRT 17.01 (iperf 3.1.4) works fine.

* Version of iperf3:
Client: Ubuntu iperf3 3.0.11, Windows 3.1.3 win64, Windows 3.1.3 x86
Server: OpenWRT 18.06 iperf3 3.5, OpenWRT snapshot iperf3 3.6

* Hardware:
Windows machines, Ubuntu machines, OpenWRT routers (several models).

* Operating system (and distribution, if any):
Windows 10 /Ubuntu 16.04/OpenWRT 18.06/SNAPSHOT

# Bug Report

* Expected Behavior
`iperf3 -s -F /usr/1GB.bin` and `iperf3 -c 192.168.1.1 -R` on the client must result in 10 second test.

* Actual Behavior
```
iperf3 -s -F /usr/1GB.bin
Accepted connection from xxxxx, port 52194
[  5] local xxx port 5201 connected to xxxx port 52196
Trace/breakpoint trap
```
and 
```iperf3 -c 192.168.1.1 -R
Connecting to host xxxx, port 5201 
Reverse mode, remote host xxxxxxxxxx is sending 
iperf3: error - control socket has closed unexpectedly
```

* Steps to Reproduce
Install iperf3 on OpenWRT 18.06 and do the test :)

* Possible Solution
...

**Comment by bmah888** [comment] 2018-09-28 17:14
Is it possible for you to test this with newer versions of iperf3 on the clients?  A number of fixes have been made since 3.0.x and 3.1.x were released, including some that are related to the use of `-R`.  So far I'm unable to reproduce this problem on iperf-3.6 builds, running between macOS and FreeBSD.  Do you think there's some dependency on OpenWRT?

I tested like so:
```
server% iperf3 -s -F /dev/zero

client% iperf3 -c server -R
```

**Comment by fleskalebas** [comment] 2018-10-19 09:45
Just tested it again with newer clients:
Alpine with iperf3 3.6 and Windows iperf3 3.6 from budman...same issue. Same with /dev/zero instead of an USB device

So I think the problem is located in the combination iperf3 - OpenWRT...

**Comment by bmah888** [comment] 2020-06-01 17:58
Repeated my testing with tip-of-master code running on CentOS 7, but unable to reproduce the problem.  I'm going to agree / presume this is related an interaction with the OpenWRT environment.  Closing this issue for now, we can reopen it if there's more information.

**Closed by bmah888** 2020-06-01 17:58 UTC
