### ISSUE TITLE
iperf3 does not work for a duration above 24h

### ISSUE THREAD

**Issue by Gryffoon** [esnet/iperf#392] opened 2016-04-13 09:23 UTC
iperf3 does not work for a duration above 24h, and this is quite annoying

**Comment by bmah888** [comment] 2016-05-20 19:05
In order for anyone to help yoiu, you'll need to provide more specific information than "does not work".  What happens and how does that differ from what you expected?

**Comment by Gryffoon** [comment] 2016-05-24 21:00
When running a test UDP above 24h with -t option, it prints an error which indicate that iperf3 thoes not work above 24h

**Comment by Yakkity** [comment] 2016-11-02 11:28
See https://github.com/esnet/iperf/issues/166   
Changing the constant to a much larger value and rebuilding should work.

**Comment by bmah888** [comment] 2016-11-17 18:13
This is a duplicate of #166, closing.

**Closed by bmah888** 2016-11-17 18:13 UTC
Labels: bug, duplicate
