### ISSUE TITLE
iperf authentication

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#342] opened 2016-01-25 10:22 UTC
Currently when we set up a iperf3 server, any client that knows that address can connect to it.

Is there any way to add some form of authentication so only approved clients can connect to the server.

**Comment by BasvanH** [comment] 2016-01-25 14:41
Search hand you will find; https://github.com/esnet/iperf/pull/242

**Comment by bmah888** [comment] 2016-01-29 16:59
Duplicate of #242.

**Closed by bmah888** 2016-01-29 16:59 UTC
Labels: duplicate
