### ISSUE TITLE
iperf3 server port refused to connect/ server busy error

### ISSUE THREAD

**Issue by purumishra** [esnet/iperf#484] opened 2016-11-29 16:29 UTC
I am using iperf 3.1.3on ubutu 14.04 machine and running it with pid file option. Even though the server is running (verified in ps -ef | grep iperf and netstat -tulnp):
ps -ef | grep iperf

root     15408     1  0 20:35 ?        00:00:00 iperf3 -s -D -p 5023 --pidfile /var/run/iperf/5023.pid

For some time iperf3 clinet is able to connect to server on the speified port but after some time getting error like connection refused, server busy, unable to write to stream socket.

When I am checking the deleted files using (lsof | grep del) the particular file for the port which is refusing connection has been deleted.
lsof | grep del
iperf3    15408             root    6u      REG              253,1     1024      55679 /tmp/iperf3.6SNn0m (deleted)
iperf3    15408             root    8u      REG              253,1     1024      55683 /tmp/iperf3.cZzSm4 (deleted)

Is this issue is coming because I am using pid file option or there is some other reason, kindly provide your suggestion.

**Comment by bmah888** [comment] 2017-03-10 02:00
Not sure what's going on here.  The socket in question is a temporary file used as a part of the test.  It's not involved in the `--pidfile` option or whether the server is able to accept connections or not.  Unlike some other UNIX servers, the iperf3 server will only accept a connection from one client at a time (this is by design)...is it possible that you're trying to have a client connect before the previous client has finished?  To rule out issues with `--pidfile` can you try omitting it?

**Comment by bmah888** [comment] 2017-05-17 20:48
Feedback timeout...closing for now.  Please re-open if you're still seeing this and have more information for us.

**Closed by bmah888** 2017-05-17 20:48 UTC
Labels: question
