### ISSUE TITLE
Bandwidth (-b) never goes below 10Mbit/sec

### ISSUE THREAD

**Issue by urskog84** [esnet/iperf#1052] opened 2020-09-12 08:21 UTC
# Bandwidth flag not working as accepted 

* Version of iperf3:
```
iperf 3.7 (cJSON 1.5.2)
Linux B450M-A 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication
```

* Operating system (and distribution, if any):
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Same problem in Win10 coputer
```
# Bug Report

* Expected Behavior
When adding -b 1K flag. I expected that Bandwidth is throttle down to 1 Kbits/sec.

have test with 1M and 5M but the Bandwidth never get below 10.5 Mbits/sec

If a test with -b 15M, i get the expected behavior

* Actual Behavior
```
iperf3.exe -c 192.168.1.219 -b 1K
Connecting to host 192.168.1.219, port 5201
[  4] local 192.168.1.212 port 52212 connected to 192.168.1.219 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.01   sec  1.38 MBytes  11.4 Mbits/sec
[  4]   1.01-2.01   sec  1.25 MBytes  10.5 Mbits/sec
[  4]   2.01-3.01   sec  1.25 MBytes  10.5 Mbits/sec
[  4]   3.01-4.01   sec  1.25 MBytes  10.5 Mbits/sec
[  4]   4.01-5.01   sec  1.25 MBytes  10.5 Mbits/sec
[  4]   5.01-6.00   sec  1.25 MBytes  10.6 Mbits/sec
[  4]   6.00-7.01   sec  1.25 MBytes  10.4 Mbits/sec
[  4]   7.01-8.00   sec  1.38 MBytes  11.7 Mbits/sec
[  4]   8.00-9.01   sec  1.25 MBytes  10.5 Mbits/sec
[  4]   9.01-10.00  sec  1.25 MBytes  10.5 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  12.8 MBytes  10.7 Mbits/sec                  sender
[  4]   0.00-10.00  sec  12.7 MBytes  10.7 Mbits/sec                  receiver

iperf Done.
```
* Steps to Reproduce
```
iperf3.exe -c 192.168.1.219 -b 1K or
iperf3.exe -c 192.168.1.219 -b 5M
```
_

**Comment by davidBar-On** [comment] 2020-09-12 14:09
This is probably because the default the TCP default buffer size is 128KB (about 10.5Mbits), and because iperf3 calculates the bitrate individually per interval, not taking into account previous intervals.  Therefore, every interval (1 second in this case) one buffer of 128KB is sent.

Reducing the buffer size below the `-b` should solve the problem.  E.g. `-l 512` for the 1K case, or `-l 8K` for the 5M case (note that `-l` is in bytes and `-b` is in bits).

**Comment by bmah888** [comment] 2020-09-14 17:37
@davidBar-On : Thanks for helping with this.  You're absolutely right.  iperf3 was designed to work in high-speed environments (multiple Gbps) and the default values for many parameters were set with this in mind.

**Comment by bmah888** [comment] 2020-10-02 18:10
Closing this issue, as I think we've got this resolved.

**Closed by bmah888** 2020-10-02 18:10 UTC

**Comment by madhura-a** [comment] 2021-01-07 14:44
Hello,

I am also observing similar behavior. I have used the command as iperf3 -c <ip> -P 50 -b 1g. The throughput obtained is 1.45 gbits/sec. Since 128KB (default value of l) < 1g, I should be able to throttle the bandwidth to 1g. But It is not getting reduced. It is very unclear to me what is the best value to choose for -l while setting -b as 1g. 

So, could you please clarify the relationship between -b and -l options?

**Comment by davidBar-On** [comment] 2021-01-07 19:34
@madhura-a, based on iperf3 code, while `--blockcount` and `--bytes` are for the whole test, `--bitrate` is per stream. 

My analysis is as follows: as you set 50 streams, and on each stream about 10.5Mbits are sent per interval (see above), it means that every round of sending, about 50*10.5=525Mbits are sent. After the 2nd send 1,050Mbits are sent, which is still bellow 1Gbits (which is about 1,073Mbits).  Therefore a send send is done and total come up to 1,575Mbits, which is close to the result you get.

To verify that this analysis is correct, can you set `-l 100K`?  If the analysis is correct, every send is now about 410Mbits, so after 3 sends limit will be reached, and throughput will be about  1.2Mbps.

**Comment by madhura-a** [comment] 2021-01-07 21:56
@davidBar-On Thank you for the explanation. 1.45Gbps is the total bit rate for all the streams. It is displayed as [sum] at the end of the experiment.

I have tried to analyze it as suggested by you. Following are the commands and the results I have obtained.

1) -P 1 -b 1g: 799Mbits/sec
2) -P 5 -b 1g: 1.35Gbits/sec
3) -P 50 -b 1g -l 100k: 1.5Gbits/sec 

Is one round means 1 second? Sorry for asking trivial questions.

**Comment by davidBar-On** [comment] 2021-01-07 22:48
@madhura-a, it seems that the your network throughput limit is about 1.5Gbps.  Also, the `-b` limit is per stream, meaning that the 1Gbps is per stream and not for the total test.  That explains why with several streams you don't get above 1.5Gbps.  However, it is not clear why with `-P 1` you got only 800Mbps and not 1Gbps.

Regarding `-l` - it defines the size of the message that is sent every time a send is performed.  By default, iperf3 sends 10 messages every time.  Therefore if you set `-l 1k`, 10KB will be sent each time, so even when you use one stream the minimum bandwidth will be 10KB/sec.

Regarding `-b` - it defines the bandwidth rate per stream.  The way iperf3 works is in bursts.  It sends as much as it can, until the amount of data per second was sent, and then it does not send anything until the next second.  As I explained above, the default quanta for the send is 10 times message size (`-l`*10).  Note that the burst size 10 can be changed using the second parameter in `-b` - `-b 1G/3` sets bandwidth to 1Gbps with burst size 3.

**Comment by madhura-a** [comment] 2021-01-12 13:06
@davidBar-On Sir, Thank you for the detailed explanation. It is working perfectly as per your explanation.
