### ISSUE TITLE
How to test multicast using iperf3

### ISSUE THREAD

**Issue by gallenX** [esnet/iperf#427] opened 2016-05-30 09:20 UTC
when using Iperf2, I can test multicast as below, for example:
Server side: iperf -s -u -B 224.0.0.5 -i 10
Client side: iperf -c 224.0.0.5 -u -b 80k –i 10 –t 92

But in iperf3, it doesn't work well. How to test multicast using iperf3? Thank you very much!

**Comment by elsticky** [comment] 2016-05-31 09:59
I'm experiencing a similar problem

on the server I did the following with iperf (2) and iperf3
iperf -c 238.1.1.10 -b 220k
iperf3 -c 238.1.1.10 -b 220k

with iperf3 I get the message 'Network is unreachable'. Do I need to do something else for iperf3?

**Comment by wifiprintguy** [comment] 2016-06-09 16:18
The answer seems to be that iperf3 currently doesn't support multicast.  If you want this feature added back in, chime in support of #27 , which for some reason has stalled.  This is very important, for instance, for Wi-Fi network profiling.

**Comment by bmah888** [comment] 2016-06-10 17:06
Duplicate of #27.

**Closed by bmah888** 2016-06-10 17:06 UTC
Labels: duplicate
