### ISSUE TITLE
supporting IPv6 multicast in CentOS7?

### ISSUE THREAD

**Issue by hoangphhut** [esnet/iperf#442] opened 2016-07-15 14:49 UTC
Hi
Does iperf3 support multicast for IPv6 on CentOS7?
I try to bind my server to an IPv6 multicast address:   iperf3 -V -s -B ff15::1
But no success. It says:
iperf 3.1.3
Linux localhost.localdomain 3.10.0-123.9.2.el7.x86_64 #1 SMP Tue Oct 28 18:05:26 UTC 2014 x86_64
iperf3: error - unable to start listener for connections: Invalid argument
Anyone can help please?
HP.

**Comment by wifiprintguy** [comment] 2016-07-15 15:39
This  is really a duplicate of Issue #27, which requests multicast support, but it hasn't been implemented yet.

**Comment by hoangphhut** [comment] 2016-07-15 16:24
Thanks. However iperf (not iperf3) already support multicast for IPv6, right?

**Comment by bmah888** [comment] 2016-08-12 21:44
This is, as indicated above, basically #27.  iperf3 doesn't support tests with multicast addresses.

**Closed by bmah888** 2016-08-12 21:44 UTC
Labels: duplicate
