### ISSUE TITLE
Windows UDP test. warning: Block size

### ISSUE THREAD

**Issue by LikHait** [esnet/iperf#659] opened 2017-10-24 19:24 UTC
# Context

* Version of iperf3:
iperf 3.2 STABLE/ master
* Operating system (and distribution, if any):
windows 10 x64(cygwin)

# Bug Report

* Expected Behavior
Successful execution with default value

* Actual Behavior
warning: Block size 401152 > sending socket buffer size 65536
warning: Block size 401152 > receiving socket buffer size 65536
Increasing socket buffer size to 402176
[ 5] local 192.168.0.101 port 52569 connected to 82.144.193.18 port 5201
iperf3: error - unable to write to stream socket: Message too long
* Steps to Reproduce
iperf3 -c xxx.xxx.xxx.xxx -u

**Comment by ralcini** [comment] 2017-10-24 20:39
in some cases the issue degenerate in #658

**Comment by bmah888** [comment] 2017-10-25 19:15
OK.  #658 and this bug seem related so I'm going to discuss both of them in this issue (@ralcini I hope that's OK with you).  As I wrote on #660, the underlying issue seems to be that `test->ctrl_sck_mss` got some strange, large value.  The code change in #660 keeps us from using that to set a block size that's too large, which is good, but that doesn't help the fact that in this situation it should have just used `DEFAULT_UDP_BLKSIZE` as the default.

Going back to this code in `iperf_connect`:

```
    int opt;
    socklen_t len;

    len = sizeof(opt);
    if (getsockopt(test->ctrl_sck, IPPROTO_TCP, TCP_MAXSEG, &opt, &len) < 0) {
	test->ctrl_sck_mss = 0;
    }
    else {
	test->ctrl_sck_mss = opt;
    }
```

If the getsockopt(3) call fails (which presumably it does on Windows earlier than Windows 10), then `test->ctrl_sck_mss` gets set to 0.  In that case, if `tcp->settings->blksize` wasn't set already, it gets `DEFAULT_UDP_BLKSIZE`.

If the getsockopt(3) call succeeds (Windows 10 and later), then `test->ctrl_sck_mss` gets some value that's reasonable, and that becomes the value of `tcp->settings->blksize` if it wasn't already set.

So I'm trying to understand how an invalid, large number could ever get into `test->settings->blksize` in the first place.  It doesn't seem to me there's a way for this to happen, unless on Windows systems it's possible for the getsockopt(3) call to return successfully _and_ put an invalid value in the `opt` variable.

OK.  Let's look at this code (same function, a little lower down):
```
    if (test->protocol->id == Pudp) {
	if (test->settings->blksize == 0) {
	    if (test->ctrl_sck_mss) {
		test->settings->blksize = test->ctrl_sck_mss;
	    }
	    else {
		test->settings->blksize = DEFAULT_UDP_BLKSIZE;
	    }
```
Would it be possible to print out the values of `test->ctrl_sck_mss` and `test->settings->blksize`, maybe just above these lines of code?  Or inside the test for `Pudp`?  Then run it and show what the values are for the failure condition?  I'd really like to understand what's going on here.  Thanks.

**Comment by ralcini** [comment] 2017-10-25 20:36
> If the getsockopt(3) call fails (which presumably it does on Windows earlier than Windows 10), then test->ctrl_sck_mss gets set to 0. In that case, if tcp->settings->blksize wasn't set already, it gets DEFAULT_UDP_BLKSIZE.

In my case, I use windows 7 64bit, but the call doesn't fail.. **opt** assume a negative value.. i don't know why. Microsoft says simply that windows 7 doesn't support TCP_MAXSEG: https://msdn.microsoft.com/it-it/library/windows/desktop/ms738544(v=vs.85).aspx

**Comment by LikHait** [comment] 2017-10-25 21:24
@ralcini  Do you get negative value only with -V option?

@bmah888 I found that the value of **opt** varies depending on the availability of option -V:
```
    int opt;
    socklen_t len;

    len = sizeof(opt);
    if (getsockopt(test->ctrl_sck, IPPROTO_TCP, TCP_MAXSEG, &opt, &len) < 0) {
	test->ctrl_sck_mss = 0;
    }
    else {
	printf("\n opt = %i \n", opt);
	test->ctrl_sck_mss = opt;
    }
```
iperf3 -c xxx.xxx.xxx.xxx -u      :  opt = 466432
iperf3 -c xxx.xxx.xxx.xxx -u -V :  opt = -2146494208

**Comment by bmah888** [comment] 2017-10-26 17:39
@LikHait:  Thanks for the testing.  That's really odd.  Like Windows is giving you a bogus value for the `TCP_MAXSEG` option, but it's not failing either.  (And this is both on Windows 10, where the option is supposedly supported, and Windows 7, where it's not.)

I don't have any explanation for the interaction with `-V` either.

**Comment by bmah888** [comment] 2017-10-27 21:39
Merged the pull request that solves this issue in #660.  Thanks!

**Closed by bmah888** 2017-10-27 21:39 UTC
Labels: bug

**Comment by ralcini** [comment] 2017-10-30 07:09
> @ralcini Do you get negative value only with -V option?

@LikHait: yes negative only with --verbose flag.. I've tried to assess the cause, but it will take a while..
