### ISSUE TITLE
UDP test fails on the server side when run over `wireguard` PtP tunnel

### ISSUE THREAD

**Issue by risa2000** [esnet/iperf#863] opened 2019-05-07 22:04 UTC
I am currently testing `wireguard` tunnel between two LANs. The routers on both sides are TL-WR1043ND v2 - cheap consumer routers, running OpenWRT image built from the active branch for this particular target.

`iperf3` version is:
```
iperf 3.6 (cJSON 1.5.2)
Linux risa-wrt 4.14.115 #0 Mon May 6 10:43:01 2019 mips
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing
```

The `wireguard` interfaces are set up with point-to-point IP addresses:
192.168.110.2 (client)
192.168.110.1 (server)
apart from that both the client and the server are routing the local networks to the other side.

Running the TCP tests (with default parameters) works correctly:
```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.110.2, port 37158
[  5] local 192.168.6.10 port 5201 connected to 192.168.110.2 port 37160
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  1.12 MBytes  9.42 Mbits/sec
[  5]   1.00-2.01   sec  1.06 MBytes  8.85 Mbits/sec
[  5]   2.01-3.00   sec  1.19 MBytes  10.0 Mbits/sec
[  5]   3.00-4.00   sec  1.12 MBytes  9.36 Mbits/sec
[  5]   4.00-5.00   sec  1.12 MBytes  9.37 Mbits/sec
[  5]   5.00-6.00   sec  1.09 MBytes  9.13 Mbits/sec
[  5]   6.00-7.00   sec  1.15 MBytes  9.64 Mbits/sec
[  5]   7.00-8.00   sec  1.14 MBytes  9.52 Mbits/sec
[  5]   8.00-9.00   sec  1.13 MBytes  9.49 Mbits/sec
[  5]   9.00-10.00  sec  1.13 MBytes  9.44 Mbits/sec
[  5]  10.00-10.10  sec   120 KBytes  9.41 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.10  sec  11.4 MBytes  9.42 Mbits/sec                  receiver
```

when running the UDP tests (with default parameters) the server bugs out with an error:
```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.110.2, port 37162
[  5] local 192.168.110.1 port 5201 connected to 192.168.110.2 port 38193
iperf3: error - unable to read from stream socket: Connection refused
```
I have already run the similar test over `openvpn` tunnel and it worked fine (as well when using direct public IP addresses of both routers). So I suspect there is something peculiar about the `wireguard` interface or routing which confuses `iperf3`.

**Comment by bmah888** [comment] 2019-05-28 20:12
Is it possible there's some kind of firewalling happening on the tunnel / tunnel endpoints, which might only affect UDP?

**Comment by risa2000** [comment] 2019-05-28 23:28
There should not be any blocking firewall rules as far as I am aware of. I however run a new test today and found an interesting point:
If I run iperf3 on each machine to bind manually to the wireguard interface, the UDP test works as expected:
```
server:~# iperf3 -s -B 192.168.110.1
client:~# iperf3 -u -B 192.168.110.2 -c 192.168.110.1
```
works OK. If I run the corresponding commands without the explicit binding and use the wireguard link address of the server for the client, i.e.:
```
server:~# iperf3 -s
client:~# iperf3 -u -c 192.168.110.1
```
it works again fine, but if I use the local server address instead of the wireguard link (which is also routed):
```
server:~# iperf3 -s
client:~# iperf3 -u -c server (where server IP is in a different subnet)
```
the server reports an error:
```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.110.2, port 59400
[  5] local 192.168.110.1 port 5201 connected to 192.168.110.2 port 34822
iperf3: error - unable to read from stream socket: Connection refused
```
From the log it seems to correctly identify both IP endpoints, but fails.

TCP tests run fine with any IP address (wireguard or local).

**Comment by bmah888** [comment] 2020-05-04 21:03
This really looks like an issue with routing, firewall rules, or both.  Going to close this issue for now, it can be re-opened if necessary.

**Closed by bmah888** 2020-05-04 21:03 UTC

**Comment by segator** [comment] 2020-05-05 17:38
have same issue, and i can confirm firewalls are full open in client and server.
I also detected for example speedtest.net it's not working when trying to start the test itself say "socket error"

**Comment by thaasoph** [comment] 2021-02-06 21:10
I think I ran into the same issue. Please keep in mind that while my analysis is based on a few educated guesses and seems conclusive to me right now, it is possible that it is completely wrong. Networking unter Linux especially with multiple interface can be tricky.
I have two peers that are directly connected to each other with WireGuard.

Peer 1 (Server):
    wg0: 10.1.0.2
    eth0: 192.168.1.4

Peer 2 (Client):
    wg0: 10.1.0.5
    eth0: 192.168.5.2

If I run iperf from peer 2 to peer 1 use peer 2's LAN-IP (192.168.1.4) as the server IP, the first datagram is sent properly and does reach it's target. However, the return datagram that is sent by the server is sent via the VPN-IP (10.1.0.2) of the server. 
The client is sending data to 192.168.1.4
The server uses the IP 10.1.0.2 to respond
The client does expect a response from 192.168.1.4 but gets datagrams from 10.1.0.2 which will be ignored.

Peer 1:
```
iperf -s
```

Peer 2:
```
iperf -c 192.168.1.4 -u
```

I have somewhat confirmed this by analyzing my WireGuard interface with tcpdump on the client
```
20:17:47.291931 IP 10.1.0.5.37155 > 192.168.1.4.5201: UDP, length 4
20:17:47.309513 IP 10.1.0.2.5201 > 10.1.0.5.37155: UDP, length 4
```

You can see that the server thinks the communication is between the two VPN-IPs and since the client does not accept the connection from the servers VPN-IP, the server throws a "Connection refused" error.
```
Accepted connection from 10.1.0.5, port 58132
[  7] local 10.1.0.2 port 5201 connected to 10.1.0.5 port 37155
iperf3: error - unable to read from stream socket: Connection refused
```

Due to time constraints I haven't actively tried to fix this issue. I'll let you know if I've found a solution.
It would be nice if someone with more in depth knowledge about Linux Networking could give me  a hint.

**Comment by davidBar-On** [comment] 2021-02-07 13:51
> You can see that the server thinks the communication is between the two VPN-IPs

What is causing the client machine to route iperf3 `eth0 (192.168.1.4)` targeted packets through `wg0 (10.1.0.5)` interface? Can you share `ip route` and `ifconfig` output?

> since the client does not accept the connection from the servers VPN-IP

I believe you are right, as for UDP iperf3 is listening to messages from the `bind` address, which is `eth0` address and not `wg0` address.

Probably on the server side, the received IP (unencrypted) packet header includes source address `192.168.1.4`.  However, since the packet came from `wg0` it is assumed that the source address is `10.1.0.5`.  If this is the case, there may be a way to workaround this issue, but for that more information about the packets on both sizes is needed.  Can you get `tcpdupmt` output on both sizes that show the IP header information (or better use the `-w` option to create a Wireshark readable files)?

**Comment by thaasoph** [comment] 2021-02-08 17:42
>What is causing the client machine to route iperf3 `eth0 (192.168.1.4)` targeted packets through `wg0 (10.1.0.5)` interface? Can you share `ip route` and `ifconfig` output?

I have added the Class-C net of each side to the others side "AllowedIps" configuration of WireGuard. The routing is therefore correct and works as intended. The two peers act as gateways to their respective net and the routing to other clients in these networks through the WireGuard tunnel works great. 

Please note, that my eth0 IPs of my peers are slightly different now.
Client: 192.168.51.2
Server: 192.168.10.4
The WireGuard IPs remain unchanged.

Client:
routes
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.51.1    0.0.0.0                 UG    202    0        0 eth0
10.1.0.1         0.0.0.0         255.255.255.255 UH    0      0        0 wg0
10.1.0.2         0.0.0.0         255.255.255.255 UH    0      0        0 wg0
192.168.10.0    0.0.0.0         255.255.255.0     U      0      0        0 wg0
192.168.51.0    0.0.0.0         255.255.255.0     U      202    0        0 eth0
```
ifconfig
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.51.2  netmask 255.255.255.0  broadcast 192.168.51.255
        inet6 fe80::5cd6:9280:dbfa:a0c  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:43:7e:99  txqueuelen 1000  (Ethernet)
        RX packets 8112539  bytes 3769061962 (3.5 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8101946  bytes 3629479562 (3.3 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1360
        inet 10.1.0.5  netmask 255.255.255.255  destination 10.1.0.5
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 5052382  bytes 6267242648 (5.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2773484  bytes 1618711552 (1.5 GiB)
        TX errors 0  dropped 455 overruns 0  carrier 0  collisions 0
```


Server:
routes
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.10.1       0.0.0.0         UG    202    0        0 eth0
10.1.0.5        0.0.0.0         255.255.255.255 UH    0      0        0 wg0
192.168.10.0    0.0.0.0         255.255.255.0   U     202    0        0 eth0
192.168.51.0    0.0.0.0         255.255.255.0   U     0      0        0 wg0
```
ifconfig
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.4  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::9762:41bd:3a87:aa18  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:24:3e:80  txqueuelen 1000  (Ethernet)
        RX packets 26236534  bytes 20234247244 (18.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 25433516  bytes 20553516179 (19.1 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1360
        inet 10.1.0.2  netmask 255.255.255.255  destination 10.1.0.2
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 2760188  bytes 1612953828 (1.5 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5054542  bytes 6269999308 (5.8 GiB)
        TX errors 21530  dropped 3 overruns 0  carrier 0  collisions 0
```

Capturing and reading the capture with Wireshark didn't work as intended. Although it logs that 2 packets have been captured, I can't actually see them when opening the files with Wireshark.

```
sudo tcpdump -i any  -nn udp port 5201 -w iperf3_capture.pcap
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
0 packets captured
2 packets received by filter
0 packets dropped by kernel
```
[iperf3_capture_udp.zip](https://github.com/esnet/iperf/files/5945551/iperf3_capture_udp.zip)


Removing the udp filter in my tcpdump command does result in more packets being captures but the udp packets are still not shown. I cannot explain this behavior.

[iperf3_capture_any.zip](https://github.com/esnet/iperf/files/5945605/iperf3_capture_any.zip)

**Comment by davidBar-On** [comment] 2021-02-08 20:56
> Although it logs that 2 packets have been captured, I can't actually see them when opening the files with Wireshark.

I also don't know why is that.  Can you run the tcpdump using `-vv` instead of `-w` (on both client and server)?

In addition, can you do the same with TCP, to allow comparing the source/target IP addresses to the UDP addresses?  (For TCP you can use `-k 1` iperf3 parameter, so only one packet will be sent.)

**Comment by thaasoph** [comment] 2021-02-10 16:20
Took me some time to get to it.
I ran the tcpdump with `-vv` and it does display a checksum error on the server side:
```
tcpdump -i any -vv -nn udp port 5201
```

Client:
```
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
16:04:48.148042 IP (tos 0x0, ttl 64, id 44366, offset 0, flags [DF], proto UDP (17), length 32)
    10.1.0.2.5201 > 10.1.0.5.47858: [udp sum ok] UDP, length 4
```

Server:
```
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
16:04:48.124672 IP (tos 0x0, ttl 64, id 44366, offset 0, flags [DF], proto UDP (17), length 32)
    10.1.0.2.5201 > 10.1.0.5.47858: [bad udp cksum 0x1426 -> 0x8ce6!] UDP, length 4
```

This is the output when running over TCP. Even with just one packet it's not short enough to add it as an inline.
[iperf3_tcp_cap.zip](https://github.com/esnet/iperf/files/5959643/iperf3_tcp_cap.zip)

I also ran the UDP test again without filtering on udp in tcpdump:
[iperf3_udp_cap.zip](https://github.com/esnet/iperf/files/5959669/iperf3_udp_cap.zip)

This however didn't show the UDP packets I was able to capture when I ran my first test with the UDP filter in place.

**Comment by davidBar-On** [comment] 2021-02-11 16:40
Unfortunately, there doesn't seem to be new information in this data.  However, from reading more about WireGuard (I a don't have it installed) I am quite sure now that the Source IP address of the UDP packet is replaced by the wg0 interface. Therefore a kind of "Source NAT" should exist, so when the wg0 is receiving a packet to the port used by iperf3, the packet's destination address will be translated back to the eth0 address.

It seems that this may be done by `iptables -SNAT`, but I am not sure exactly how.  There are many related questions and answers related to WireGuard or VPN in genral, so if you are willing to try, you may be able to setup the right configuration.  E.g. see:
https://www.cyberciti.biz/faq/how-to-set-up-wireguard-firewall-rules-in-linux/
https://serverfault.com/questions/1042620/preserve-source-ip-on-wireguard-vpn-setup-without-using-ip-route
https://terrywang.net/2016/02/02/new-iptables-gotchas.html

(If you will be able to solve the issue or at least able to make a progress, please let us know.)
