### ISSUE TITLE
Problem with iperf running in background for more than 5min

### ISSUE THREAD

**Issue by josecarlosjr** [esnet/iperf#661] opened 2017-10-27 20:12 UTC
# Context

* Version of iperf3:
  Version of iperf3:
    Installed: **3.1.3-1**
    Candidate: **3.1.3-1**
    Table of version:
        *** 3.1.3-1 500

over oracle virtual box:
version 5.0.40_ubuntu r115130

* Hardware:
Intel Core i7 7500U
memory: 16gb
ssd: 275gb

* Operating system (and distribution, if any):
Operating System:
Distributor ID:	**Ubuntu**
Description:	**Ubuntu 17.04**
Release:	**17.04**
Codename:	**zesty**

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

I'm running iperf3 between hosts on **Minnet v2.2.2**

* Expected Behavior

successful execution till the time limit using the flag '**&**' at the end of the command (to run in background mode).

* Actual Behavior
**after approximately 5 min of running the results goes all zeros**

...
...
[  4] 306.00-307.00 sec  2.38 MBytes  20.0 Mbits/sec  305  
[  4] 307.00-308.00 sec  2.38 MBytes  20.0 Mbits/sec  305  
[  4] 308.00-309.00 sec  2.38 MBytes  20.0 Mbits/sec  305  
[  4] 309.00-310.00 sec  2.40 MBytes  20.1 Mbits/sec  307  
[  4] 310.00-311.00 sec  2.38 MBytes  19.9 Mbits/sec  304  
[  4] 311.00-312.00 sec  2.38 MBytes  20.0 Mbits/sec  305  
[  4] 312.00-313.00 sec  2.38 MBytes  20.0 Mbits/sec  305  
[  4] 313.00-314.00 sec  2.38 MBytes  20.0 Mbits/sec  305  
[  4] 314.00-375.47 sec  8.00 KBytes  1.07 Kbits/sec  1  
[  4] 375.47-375.47 sec  0.00 Bytes  0.00 bits/sec  0  
[  4] 375.47-375.47 sec  0.00 Bytes  0.00 bits/sec  0  
[  4] 375.47-375.47 sec  0.00 Bytes  0.00 bits/sec  0  
[  4] 375.47-375.47 sec  0.00 Bytes  0.00 bits/sec  0  
[  4] 375.47-375.47 sec  0.00 Bytes  0.00 bits/sec  0  
[  4] 375.47-375.48 sec  0.00 Bytes  0.00 bits/sec  0  
[  4] 375.48-375.48 sec  0.00 Bytes  0.00 bits/sec  0  
[  4] 375.48-375.48 sec  0.00 Bytes  0.00 bits/sec  0  
[  4] 375.48-375.48 sec  0.00 Bytes  0.00 bits/sec  0  
[  4] 375.48-375.48 sec  0.00 Bytes  0.00 bits/sec  0
...
...

* Steps to Reproduce

just put any iperf3 variation in background for more de 5 min
e.g **iperf3 -c <ip> -p 5202 -u -b 20M -i 1 -t 86100 &**

**Comment by bmah888** [comment] 2017-10-27 20:49
I tried this for over 1000 seconds on a CentOS 7 system and had no issues.  Other people have run tests for many hours.  I wonder if there's some timeout happening due to the mininet environment, or something like that.  You should probably try running a test with both the client and server on the same host, TCP, not running in background, etc. to try to narrow down what the problem is.

Another thing...consider using a newer iperf3, especially if you are doing UDP tests.  In iperf-3.2 we changed some aspects of how pacing works, which should lead to less bursty behavior and fewer self-induced packet drops with UDP tests.

This really feels more like a support question than a bug in iperf3, so I'm going to close this issue for now.  If you are still having problems after doing some basic debugging, please send an email to the iperf-users@sourceforge.net mailing list and we'll take it up there.  Thanks.

**Closed by bmah888** 2017-10-27 20:49 UTC

**Comment by josecarlosjr** [comment] 2017-10-27 21:14
Hi there,
For my experiment, I need to run it in background because I'm running multiple iperf tests on mininet via python script. I've tried in a virtual machine on VMWare with no success.

On foreground I have no issue. My problem is running multiple iperf clients on background.
Ok i will try to download the newest version of iperf.

Thank you!

**Comment by josecarlosjr** [comment] 2018-09-17 15:15
Hi there... 

As I said long time ago, every time when I was executing my experiment with traffic generating with iperf, after 5 min approximately all the results was going zero.

What I did was using the command **nohup** in front of the command **iperf**.
**"no hangup" the (HUP) signal**

With this command I was able to let the iperf command running for over a day (86400 sec) generating multiples traffics on background.

Hope I could give some help

**Comment by soeyehtet1993** [comment] 2018-09-17 15:43
Dear,

Thanks for your information. I face the same problem with you. I hope your
suggestion can fix my problem too.

Best Regards,
Soe Ye Htet
