### ISSUE TITLE
Wrong summary reported at end of UDP test on client and server

### ISSUE THREAD

**Issue by BCITMike** [esnet/iperf#238] opened 2015-01-13 19:55 UTC
I suspect this issue is specific to me or my setup, as I can't see how this bug would make it through 3.08-3.11 without being noticed.

I am trying to test wireless traffic at different modulations, which should give increasing throughput in steps. Instead, my results were pretty consistently higher than expected. Upon further investigation, it seems the sender side load is being reported instead of the client side ACTUAL received. I had to revert to iperf2 to get valid results for the test.

Both PC's are Ubuntu 14.04. Initially noticed with 3.0.8, but confirmed with both 3.0.11 download and latest git pull yesterday.

Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:    14.04
Codename:   trusty

iperf3 -v
iperf 3-CURRENT
Linux left 3.13.0-30-generic #54-Ubuntu SMP Mon Jun 9 22:45:01 UTC 2014 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy

As you can see in the server reporting side, its reporting what the sending side's load was, not what it actually measured/received.  It should have reported something around 10Mbits/sec, not 94.0Mbits/sec.  My testing doesn't usually send this high of a load when its on a lower modulation, but I'll send 25Mbps expecting to get 22Mbps, and it reports 25Mbps, which is still incorrect and misleading.

Client PC:
# iperf3 -c 192.168.1.60 -p 5201 -u -Z -b 99M -t 10

Connecting to host 192.168.1.60, port 5201
[  4] local 192.168.1.50 port 37972 connected to 192.168.1.60 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec  10.4 MBytes  86.9 Mbits/sec  1326  
[  4]   1.00-2.00   sec  11.4 MBytes  95.8 Mbits/sec  1462  
[  4]   2.00-3.00   sec  11.4 MBytes  95.8 Mbits/sec  1462  
[  4]   3.00-4.00   sec  11.4 MBytes  95.9 Mbits/sec  1463  
[  4]   4.00-5.00   sec  11.4 MBytes  95.8 Mbits/sec  1462  
[  4]   5.00-6.00   sec  11.4 MBytes  95.9 Mbits/sec  1463  
[  4]   6.00-7.00   sec  11.4 MBytes  95.8 Mbits/sec  1462  
[  4]   7.00-8.00   sec  11.4 MBytes  95.8 Mbits/sec  1462  
[  4]   8.00-9.00   sec  11.4 MBytes  95.9 Mbits/sec  1463  
[  4]   9.00-10.00  sec  11.4 MBytes  95.8 Mbits/sec  1462  

---

[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.00  sec   113 MBytes  94.9 Mbits/sec  0.645 ms  12553/14317 (88%)  
[  4] Sent 14317 datagrams

iperf Done.

---

Server PC:
# iperf3 -s -i1

---
## Server listening on 5201

Accepted connection from 192.168.1.50, port 36590
[  5] local 192.168.1.60 port 5201 connected to 192.168.1.50 port 37972
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  1.64 MBytes  13.8 Mbits/sec  0.604 ms  806/1016 (79%)  
[  5]   1.00-2.00   sec  1.62 MBytes  13.6 Mbits/sec  0.492 ms  1252/1459 (86%)  
[  5]   2.00-3.00   sec  1.46 MBytes  12.3 Mbits/sec  0.568 ms  1261/1448 (87%)  
[  5]   3.00-4.00   sec  1.33 MBytes  11.1 Mbits/sec  0.376 ms  1295/1465 (88%)  
[  5]   4.00-5.00   sec  1.28 MBytes  10.7 Mbits/sec  0.602 ms  1315/1479 (89%)  
[  5]   5.00-6.00   sec  1.38 MBytes  11.5 Mbits/sec  0.404 ms  1282/1458 (88%)  
[  5]   6.00-7.00   sec  1.28 MBytes  10.7 Mbits/sec  0.527 ms  1293/1457 (89%)  
[  5]   7.00-8.00   sec  1.32 MBytes  11.1 Mbits/sec  0.444 ms  1281/1450 (88%)  
[  5]   8.00-9.00   sec  1.18 MBytes  9.90 Mbits/sec  0.530 ms  1330/1481 (90%)  
[  5]   9.00-10.00  sec  1.18 MBytes  9.90 Mbits/sec  0.554 ms  1304/1455 (90%)  
[  5]  10.00-10.10  sec   120 KBytes  10.1 Mbits/sec  0.645 ms  134/149 (90%)  

---

[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
## Server listening on 5201

Am I the only one seeing this problem? I assume so, as this should be very noticeable. 
Thanks

**Comment by BCITMike** [comment] 2015-02-13 22:20
Wow! No one can even say "this isn't happening for me" or "this is happening for me"?  This is such an obvious and seriously bad (IMO) bug (I would call this a showstopper bug and delay release until fixed), that either this should be fixed ASAP or a problem on this Ubuntu platform.  It would be good to know if others are seeing the same thing so I can rule out my Ubuntu setup.  It's fairly useless as a test tool if it reports the incorrect throughput.

**Comment by bmah888** [comment] 2015-03-13 20:42
I think what's going on here is that the summary results are confusing about which parts are coming from the sender side and which parts from the receiver side.  The interval and bandwidth are coming from the sender.  The jitter and lost/total datagram counts are from the receiver (because those are only known on the receiver).  (Notice I left out the transfer column.  I need to do a little more study to see where that's coming from.)

It sounds to me like you were expecting the bandwidth to be the goodput that was measured on the receiver.  Clearly it's not.

A reason that measuring the sender's bitrate is that at least in the environment iperf3 was designed for, it's very possible that throughput is limited by hosts that can't send fast enough.  So we do need to measure that.  So that part is actually (I believe) working as designed.

I don't think there's a bug here, but I'm attaching labels to it just to make sure we get a resolution.

**Comment by BCITMike** [comment] 2015-03-13 20:58
Bob,

TCP is incorrectly reporting sending side instead of receiving side as well.  I'll see if I can get some logs of this.  Basically, I have simple linux scripts to change data rates on wifi and output to text files the results, where I expect increasing steps of goodput at higher rates.  When I switched from iperf2 to iperf3 results, the results were noticeably better and I thought that was from bug fixes and optimizations in iperf, but I later found out it was the result of the incorrect reporting.

If there is a specific scenario in UDP you want to try, let me know.

**Comment by purumishra** [comment] 2017-02-01 16:53
Hi Bruce ,
      I am using iperf 3.1.3 and facing the same issue which is wrong loss info provided by iperf3 .
      I ran iperf3 client and server and verified the packet drop with tcpdump, while tcpdump is showing 0.2% packet loss iperf3 is showing 50% packet loss.
    The same test in same environment working fine for iperf2.
     Any help on this issue is appreciated.

**Comment by bmah888** [comment] 2017-04-21 17:05
@purumishra:  The issue you reported is a different problem.  Please re-test with iperf3 3.1.5 or newer; we made some changes to the default UDP send sizes that should fix this problem.

**Comment by bltierney** [comment] 2017-04-29 16:29
I believe this is now acting as expected. For UDP tests, the sender reports what its sending, and the receiver reports what its receiving.

While confirming this, I found another issue however, reported in #560

I'm closing this one, but feel free to reopen or create new issue if you disagree.

**Comment by BCITMike** [comment] 2017-04-29 20:58
No, I would say an attempt at fixing this was made by adding sending/receiving tags (which is a good solution), but not actually working properly. The reported problem was incorrect summary for both sender and receiver. As of 3.1.6, sender side reports properly, but receiver side fails for both UDP and TCP tests.

For UDP, it doesn't show any sender stats (it did before), and incorrectly shows 0 bits/sec for received.
For TCP, sender side has both correct, receiver side has sender stats incorrectly shows 0 bits/sec for received.

# iperf3 -v
iperf 3.1.6

Server listening on 5201
-----------------------------------------------------------
Accepted connection from 104.254.xx.xx, port 35396
[  5] local 172.x.xx.xxx port 5201 connected to 104.254.xx.xx port 35398
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec   638 KBytes  5.23 Mbits/sec
[  5]   1.00-2.00   sec  2.87 MBytes  24.1 Mbits/sec
[  5]   2.00-3.00   sec  4.08 MBytes  34.2 Mbits/sec
[  5]   3.00-4.00   sec  2.99 MBytes  25.1 Mbits/sec
[  5]   4.00-5.00   sec  2.92 MBytes  24.5 Mbits/sec
[  5]   5.00-6.00   sec  3.19 MBytes  26.8 Mbits/sec
[  5]   6.00-7.00   sec  3.21 MBytes  26.9 Mbits/sec
[  5]   7.00-8.00   sec  3.16 MBytes  26.5 Mbits/sec
[  5]   8.00-9.00   sec  3.10 MBytes  26.0 Mbits/sec
[  5]   9.00-10.00  sec  3.25 MBytes  27.3 Mbits/sec
[  5]  10.00-10.12  sec   382 KBytes  27.2 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.12  sec  **0.00 Bytes  0.00 bits/sec**                  sender
[  5]   0.00-10.12  sec  29.8 MBytes  24.7 Mbits/sec                  receiver


Sender side summary:
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  32.9 MBytes  27.6 Mbits/sec  1225             sender
[  4]   0.00-10.00  sec  29.8 MBytes  25.0 Mbits/sec                  receiver

So, disagreeing numbers. There is really no reason for the receiver side to disagree. The receiver reports the number to sender, sender displays it. Not sure why it should differ. The sender side receiver number is not correct.

It is good practice to close bug issues by clearly stating what the fix was (ie, pasting output to match the reported bug's output) and where it was committed. Otherwise, it would be clear the bug isn't fixed.  Closing bugs should be after they are verified.  This bug should never had been released and should not be lingering for over two years.  I just don't know what I'm missing as to how this wasn't a showstopper issue for more people than just me.

**Closed** 2017-05-03 17:21 UTC
Labels: bug

**Comment by bmah888** [comment] 2017-05-03 17:23
Test output here:

https://github.com/esnet/iperf/issues/560#issuecomment-298967379
