### ISSUE TITLE
UDP sending is bursty

### ISSUE THREAD

**Issue by mpitt** [esnet/iperf#386] opened 2016-03-21 15:58 UTC
I found this issue while debugging some strange packet loss happening over UDP with a bandwidth setting (`-b`) much lower than the link/path capacity. I was working under the assumption that using the `-b` flag would result in a nice constant-bitrate traffic, but this turned out to be wrong.

Some plots to show why. These are packet captures from the sender, as seen through Wireshark IO graph module, with a granularity of 0.01 s.

![iperf-server](https://cloud.githubusercontent.com/assets/690682/13924004/f1c212e4-ef82-11e5-9048-8d5bf0cae11b.png)
The first plot shows the behaviour of iperf2 (`-u -b 30M`). The sending rate is quite stable over the whole test. The receiver reports a 30 Mbit/s achieved throughput, with ~0 packet loss.

![iperf3-server](https://cloud.githubusercontent.com/assets/690682/13924137/78dd3dee-ef83-11e5-95be-507dae663521.png)
Next, we have iperf3 (`-u -b 30M -l 1470`, the packet size is set in order to avoid IP fragmentation). We see a very bursty sending rate. Note the Y-axis max, which is 1 order of magnitude bigger than the previous plot. In this case, I observe a 20-25% packet loss, with an according reduction in achieved throughput, as a router in the middle starts dropping packets.

![iperf3-server-small](https://cloud.githubusercontent.com/assets/690682/13924410/8f8dce9a-ef84-11e5-8aec-08b574abc2d5.png)
Finally, I started fiddling with the send buffer (`-w`). This last plot shows iperf 3 with `-u -b 30M -l 1470 -w 14700` (the send buffer takes 10 packets). Maybe it's hard to see from the plot, but the send rate smooths out quite a bit, coming closer to a 50/50 duty cycle. The peaks are also lower (~105 vs. ~360). The most interesting observation: with this settings packet loss disappears.

I don't know if this burstiness is desired behaviour, but I have some objections to it:
- it is not intuitive, as a naïve user like me would assume a constant bitrate;
- it produces results that are difficult to explain;
- I think it might be related to #296, or at least to @grad-michal’s comment on that issue.

**Comment by DeHackEd** [comment] 2016-04-06 14:02
I have seen issues caused by this where a sender on a fast port (eg: gigabit) sending to a receiver on a slow port (eg: 100 megabits) will experience severe packet loss due to switch buffers being overloaded and packets dropped. Even with a setting of `-b 20M -l 1200` the 100 megabit receiver will experience >75% packet loss.

iPerf version 2 did not have this issue.

**Comment by skydevil56** [comment] 2016-04-27 20:19
I have the same problem. Please fix it, because of this problem iperf3 can not be used for UDP tests :(

**Comment by folsson** [comment] 2016-06-28 14:09
The throttling algorithm seems to be working on 100ms intervals (https://github.com/esnet/iperf/blob/master/src/iperf_api.c#L1203).
Increasing the frequency of this check (i.e. lower 100000L to something like 1000L) seems to smooth out the bursts.
The reason why increasing the size of the send buffer (-w) somewhat mitigates this problem is (probably) because the buffer "absorbs" the burst (as it's is intended to do), but you never set it even close to the size needed to handle these kinds of spikes (when testing "high speed links").

**Comment by mpitt** [comment] 2016-07-05 13:13
> Increasing the frequency of this check (i.e. lower 100000L to something like 1000L) seems to smooth out the bursts.

Good suggestion!

> The reason why increasing the size of the send buffer (-w) somewhat mitigates this problem is (probably) because the buffer "absorbs" the burst

Actually, here the problem was mitigated by *reducing* the buffer size. The packets are not dropped at the sender, so increasing the buffer there wouldn't help. The drops occur at a crappy consumer grade router/access point in the path, which can't handle Gigabit traffic bursts. So reducing the buffer helps because packets are sent at a burst rate lower than the link speed (but the average rate still achieves the `-b` target).

One other possible solution is to put a shaping buffer (token bucket) between the server and this crappy router, and set it to a speed higher than `-b` but lower than Gigabit (300 Mb/s seems to satisfy my router).

**Comment by DeHackEd** [comment] 2016-07-06 01:03
Actually even "high end" switches have this problem. I tested on a Juniper EX-2200 (office-class switch). The trend is that switching ASICs have small buffers which are already divided between all the ports for the QoS queues.

**Comment by bmah888** [comment] 2016-07-06 01:46
If you are running iperf-3.1.3 or later or recent Linux, it can do fair-queue based flow control at the socket level, which should smooth out the bursts at the device driver level.

**Comment by mpitt** [comment] 2016-07-06 10:02
New test with latest master (`099244e`), enabling FQ scheduling and pacing.
(Note to future testers: remember to actually enable the scheduler `tc qdisc add dev $ETH root fq`)

Results look very similar to what I expected and to iperf2.
![iperf3-fq](https://cloud.githubusercontent.com/assets/690682/16614397/48489060-4371-11e6-96c2-c5712c9d0c64.png)

I still think we might want a solution for non-Linux systems though.

**Comment by bmah888** [comment] 2017-04-14 18:22
We believe we have a fix for this in #460...currently on master but not (yet) in a release.  Closing.

**Closed by bmah888** 2017-04-14 18:22 UTC
