### ISSUE TITLE
iperf_set_test_client_rsa_pubkey() API call always fails to set public key

### ISSUE THREAD

**Issue by oleh-yudin-ring** [esnet/iperf#940] opened 2019-12-11 14:31 UTC
# Context

* Version of iperf3:
3.7

# Bug Report

* Expected Behavior
When using iperf_set_test_client_ username/password/rsa_pubkey C API it is expected these data to be passed to server

This is not happening due to load_pubkey_from_base64() doesn't work as expected.
In addition there is a leak of bio pointer allocated data.
Also the same is related to load_privkey_from_base64().

* Actual Behavior
Authentication data is not sent to server (test->settings->authtoken is empty) for the test during test run

* Steps to Reproduce

1. Via C API setup test with iperf_set_test_client_ username/password/rsa_pubkey
2. Run test and see auth failure error

* Possible Solution
There is no need to do Base64Decode() cause PEM_read_bio_PUBKEY() already requires base64 key string in PEM format with corresponding header and footer to work correctly.
Or find a different way to set raw RSA key data into OpenSSL EVP_PKEY
The following solution worked for me:
```
EVP_PKEY *load_pubkey_from_base64(const char *buffer) {
    BIO* bio = BIO_new(BIO_s_mem());
    BIO_puts(bio, "-----BEGIN PUBLIC KEY-----\n");
    BIO_puts(bio, buffer);
    BIO_puts(bio, "\n-----END PUBLIC KEY-----\n");
    EVP_PKEY *pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);
    BIO_free(bio);
    return (pkey);
}
```

**Comment by bmah888** [comment] 2019-12-23 18:22
I don't do any OpenSSL programming myself.  I am trying to figure out what the semantics of `load_pubkey_from_base64()` are, or rather what the desired functionality is.

I would have thought that the input to this function (whatever its name is) would just have been the same as the file contents that `load_pubkey_from_file()` takes.  Instead it looks like it's trying to take the base64-encoded part of the file minus the beginning and ending lines.

@ralcini When you implemented these API call, what did you have in mind?  What is supposed to be in the block of memory pointed to by the `buffer` parameter?

@FuzzyStatic Have you tried using the new API calls?  Did this include `load_pubkey_from_base64()` and `load_privkey_from_base64()`?

**Comment by bmah888** [comment] 2019-12-23 18:25
@oleh-yudin-ring I think that your comment about leaking memory is referring to the fact that the `bio` buffer is not deallocated after `pkey` is created.  Is that right?

**Comment by oleh-yudin-ring** [comment] 2019-12-23 18:42
@bmah888 Yes, that's right, with the memory leak I meant that bio is not freed. 
And regarding your previous comment I would say that on my opinion load_pubkey_from_base64() should NOT require PEM header and footer to be included into input as it goes to the public API. Thus to make this more clear from naming perspective I would propose renaming load_pubkey_from_file() to load_pub_key_from_pem_file(). and one more thing: as far as I know OpenSSL until 1.1 doesn't have functionality to load key from plain base64 string. Therefore you may use my suggested fix to keep compliance with older versions of OpenSSL if you meant to.

**Comment by bmah888** [comment] 2020-01-02 19:18
@oleh-yudin-ring Thanks for the follow-up.  I'd like to hear from the people who requested and implemented these API calls what they had in mind.  I acknowledge this doesn't work as written, but I'm not sure what the intended behavior was.

**Comment by FuzzyStatic** [comment] 2020-01-02 19:27
The current implementation works for me, but I am willing to test this if the consensus is that it's a better implementation.

**Comment by ralcini** [comment] 2020-01-02 22:03
Hi @oleh-yudin-ring I don't understand why you expect that

> Expected Behavior
When using iperf_set_test_client_ username/password/rsa_pubkey C API it is expected these data to be passed to server

The server must receive only the encripted token containing all the data, remember that the communication channel is not encrypted. 

Can you better explain/detail what you do at the step 2?

> Steps to Reproduce
1 Via C API setup test with iperf_set_test_client_ username/password/rsa_pubkey
2 Run test and see auth failure error

**Comment by ralcini** [comment] 2020-01-02 22:22
@oleh-yudin-ring: the original use case that I had in mind was that a client using the api must load in memory the content of public key and then passing it to the API in a safe way and without have any interest in managing its content. I think that the base64 encoding can reach the goal.

Sure, we can optimize the function and remove the base64 encoding, but... it's an optimization for you or a real bug?

**Comment by oleh-yudin-ring** [comment] 2020-01-02 22:34
Hello @ralcini!
> The server must receive only the encripted token containing all the data, remember that the communication channel is not encrypted.

Yes, I know. I meant that username/password are converted into token which then being encrypted with public key and passed to server via JSON, right?

At step 2) I just call iperf_run_client() to start the test.

It's a real bug I encountered. Hope the explanation below will be more clear:
What I see is that public key is not set due to an error in load_pubkey_from_base64(). Means settings->client_rsa_pubkey still NULL after function call.
This leads to the following condition is false and auth settings are not being delivered to server:
```
if (test->settings->client_username && test->settings->client_password && test->settings->client_rsa_pubkey){
        encode_auth_setting(test->settings->client_username, test->settings->client_password, test->settings->client_rsa_pubkey, &test->settings->authtoken);
        cJSON_AddStringToObject(j, "authtoken", test->settings->authtoken);
    }
```

**Comment by oleh-yudin-ring** [comment] 2020-01-02 22:43
@FuzzyStatic, @ralcini 
```
EVP_PKEY *load_pubkey_from_base64(const char *buffer) {
    unsigned char *key = NULL;
    size_t key_len;
    Base64Decode(buffer, &key, &key_len);

    BIO* bio = BIO_new(BIO_s_mem());
    BIO_write(bio, key, key_len);
    EVP_PKEY *pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);
    return (pkey);
}
```
Let's take a closer look at this function code:
As far as I'm aware PEM_read_bio_PUBKEY() expects a text input in PEM format with base64 key in it. But according to implementation you pass binary public key data decoded from base64 argument after Base64Decode. 
I'm not sure about latest version of OpenSSL but as I use v1.02 this code doesn't work for me at all.
In addition:
bio here is just an OpenSSL container. But you must free the memory allocated by it using BIO_free, isn't it?

**Comment by FuzzyStatic** [comment] 2020-01-03 03:47
@oleh-yudin-ring how are you setting up your code?

Here is a sample of code I know works:

```
 #if defined(HAVE_SSL)
    iperf_set_test_client_username(test, "username");
    iperf_set_test_client_password(test, "password");
    // Base 64 encoded key is passed here
    iperf_set_test_client_rsa_pubkey(test, "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDLzViaUZPdXR1VGNSZlg1c0tiS2NTTkxYdwpBT3pxOUs0aE1BVDlXNzZuSENXYmtockJvOUd3YTFYZFBvSU5MMEFzaDUvcUpZSkFtVWliSm1TSnBrNnc5YXZrCldPY2V6MjJ1Y0FjMUcvL1g5c1RYYkM1UWxVRzJoNDgzejVpbkJNbkVvSHN4ZTlPTTlVUTc5MmZKVVdGVUswTUEKMVFEb0ZUeHhwdUtjVGhxNnZRSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==");
#endif
```

This is with a public key that looks like:

```
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/5biFOutuTcRfX5sKbKcSNLXw
AOzq9K4hMAT9W76nHCWbkhrBo9Gwa1XdPoINL0Ash5/qJYJAmUibJmSJpk6w9avk
WOcez22ucAc1G//X9sTXbC5QlUG2h483z5inBMnEoHsxe9OM9UQ792fJUWFUK0MA
1QDoFTxxpuKcThq6vQIDAQAB
-----END PUBLIC KEY-----
```

This is with:

```
openssl version
OpenSSL 1.0.2s  28 May 2019
```

Maybe you are confused about what to pass into the function, you have to base64 encode your key first (see https://www.base64encode.org/). The function is not base64 decoding
```
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/5biFOutuTcRfX5sKbKcSNLXw
AOzq9K4hMAT9W76nHCWbkhrBo9Gwa1XdPoINL0Ash5/qJYJAmUibJmSJpk6w9avk
WOcez22ucAc1G//X9sTXbC5QlUG2h483z5inBMnEoHsxe9OM9UQ792fJUWFUK0MA
1QDoFTxxpuKcThq6vQIDAQAB
-----END PUBLIC KEY-----
```

but is base64 decoding

```
LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDLzViaUZPdXR1VGNSZlg1c0tiS2NTTkxYdwpBT3pxOUs0aE1BVDlXNzZuSENXYmtockJvOUd3YTFYZFBvSU5MMEFzaDUvcUpZSkFtVWliSm1TSnBrNnc5YXZrCldPY2V6MjJ1Y0FjMUcvL1g5c1RYYkM1UWxVRzJoNDgzejVpbkJNbkVvSHN4ZTlPTTlVUTc5MmZKVVdGVUswTUEKMVFEb0ZUeHhwdUtjVGhxNnZRSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
``` 

into the original representation.

If you are still having issues, please provide some code samples and your operating system.

**Comment by oleh-yudin-ring** [comment] 2020-01-03 09:11
@FuzzyStatic
Ok, now I see what you're doing. What you call a 'public key' here is not actually a public encryption key but PEM representation of public encryption key. PEM format already contains base64 of the binary key inside it between "-----BEGIN PUBLIC KEY-----" and "-----END PUBLIC KEY-----". 
So basically you did DOUBLE base64 encoding of the binary key which I couldn't imagine you would. 
Why would you? PEM is already in text format and could be transferred as is in any JSON or XML. There is no need to base64 encode it over again, is there?
In my infrastructure we just use raw public key which is base64 encoded to be transferred.
Could you add specific API method for that IMHO it would be a right thing to do, don't you think?
And, please, don't forget to fix that memory leak for bio I mentioned.
Thanks!

**Comment by FuzzyStatic** [comment] 2020-01-03 09:24
I do not agree that it is the right thing to do. The key inside may be base64 encoded, but it also contains line terminators and the unencoded header and footer, which can cause difficulty passing the key between different systems and you cannot assume the header is always the same. Having a single string without any termination is much easier to implement from system to system. The API does not need to contain human readable formats, and instead should have easy to implement formats for all situations. Base64 encoding is universal to all major languages. Maybe this can be better communicated in the documentation.

As for the free, I'll leave that to @ralcini since they first implemented the API.

**Comment by ralcini** [comment] 2020-01-03 10:29
@oleh-yudin-ring sorry, for the memory leak I agree with you adding BIO_free(bio); after creating EVP_PKEY. Can you submit the patch with a PR?

**Comment by bmah888** [comment] 2020-01-03 17:56
Just wanted to say thanks to all for discussing this issue.  I'm learning a bunch just by reading your posts.  Aside from the `BIO_free()` issue, seems to me this comes down to...in this function:
```
EVP_PKEY *load_pubkey_from_base64(const char *buffer)
```
What exactly is supposed to be in `buffer`?  (Like what information, and how is it supposed to be represented?)  Once we agree on what that is, it's just a matter of making the code support it (if it doesn't already), and documenting the heck out of it so nobody gets confused in the future.

**Comment by FuzzyStatic** [comment] 2020-01-03 18:05
@bmah888,

No one should be using `EVP_PKEY *load_pubkey_from_base64(const char *buffer)` or `load_privkey_from_base64` and instead should be using:

```
void    iperf_set_test_client_rsa_pubkey(struct iperf_test *ipt, char *client_rsa_pubkey_base64);
void    iperf_set_test_server_rsa_privkey(struct iperf_test *ipt, char *server_rsa_privkey_base64);
```

For a public key, it needs to be base64 encoded. so for a public kkey like:

```
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/5biFOutuTcRfX5sKbKcSNLXw
AOzq9K4hMAT9W76nHCWbkhrBo9Gwa1XdPoINL0Ash5/qJYJAmUibJmSJpk6w9avk
WOcez22ucAc1G//X9sTXbC5QlUG2h483z5inBMnEoHsxe9OM9UQ792fJUWFUK0MA
1QDoFTxxpuKcThq6vQIDAQAB
-----END PUBLIC KEY-----
```

`char *client_rsa_pubkey_base64` becomes:

```
LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDLzViaUZPdXR1VGNSZlg1c0tiS2NTTkxYdwpBT3pxOUs0aE1BVDlXNzZuSENXYmtockJvOUd3YTFYZFBvSU5MMEFzaDUvcUpZSkFtVWliSm1TSnBrNnc5YXZrCldPY2V6MjJ1Y0FjMUcvL1g5c1RYYkM1UWxVRzJoNDgzejVpbkJNbkVvSHN4ZTlPTTlVUTc5MmZKVVdGVUswTUEKMVFEb0ZUeHhwdUtjVGhxNnZRSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
```

You can use https://www.base64encode.org/ and input the public key to see how the encoding works.

**Comment by bmah888** [comment] 2020-01-03 18:43
@FuzzyStatic I stand corrected, thanks!  Still learning...

**Comment by bmah888** [comment] 2020-04-16 16:49
I have completely lost track of this discussion, apologies.  Are we done here?

**Comment by FuzzyStatic** [comment] 2020-04-17 00:05
I am good with these changes.

**Comment by oleh-yudin-ring** [comment] 2020-04-17 00:06
Yes, memory leaks are fixed. The API still looks weird for me with this double base64 stuff but I guess the issue could be close as soon it's so by design

**Comment by bmah888** [comment] 2020-04-17 14:56
OK.  I'll go ahead and close this then, thanks.

**Closed by bmah888** 2020-04-17 14:56 UTC
Labels: bug
