### ISSUE TITLE
-F option will not work in Windows

### ISSUE THREAD

**Issue by HendersonD2** [esnet/iperf#318] opened 2015-10-26 20:54 UTC
I am using a Windows 2012 R2 box as a iPerf server
I am using my Win7 machine as a client. When I just test throughput iPerf works fine as shown below. When I attempt to use the -F command and transfer a large file it stops after just transferring 5% of the file. I run the same -F command on a Mac and it transfer the entire file. Is this a bug or am I doing something wrong?

C:\iperf>iperf3 -c 10.121.125.66
Connecting to host 10.121.125.66, port 5201
[  4] local 10.121.88.13 port 49799 connected to 10.121.125.66 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.01   sec   110 MBytes   912 Mbits/sec
[  4]   1.01-2.01   sec   110 MBytes   920 Mbits/sec
[  4]   2.01-3.01   sec   111 MBytes   933 Mbits/sec
[  4]   3.01-4.01   sec   112 MBytes   941 Mbits/sec
[  4]   4.01-5.01   sec   112 MBytes   941 Mbits/sec
[  4]   5.01-6.01   sec   111 MBytes   934 Mbits/sec
[  4]   6.01-7.00   sec   112 MBytes   941 Mbits/sec
[  4]   7.00-8.00   sec   112 MBytes   940 Mbits/sec
[  4]   8.00-9.00   sec   112 MBytes   940 Mbits/sec
[  4]   9.00-10.01  sec   112 MBytes   941 Mbits/sec

---

[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.01  sec  1.09 GBytes   934 Mbits/sec                  sender
[  4]   0.00-10.01  sec  1.09 GBytes   934 Mbits/sec                  receiver

iperf Done.

C:\iperf>iperf3 -c 10.121.125.66 -t 20 -F Part19.cab
Connecting to host 10.121.125.66, port 5201
[  4] local 10.121.88.13 port 49803 connected to 10.121.125.66 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-0.50   sec  56.0 MBytes   942 Mbits/sec

---

[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-0.50   sec  56.0 MBytes   942 Mbits/sec                  sender
        Sent 56.0 MByte / 1.09 GByte (5%) of Part19.cab
[  4]   0.00-0.50   sec  56.0 MBytes   942 Mbits/sec                  receiver

iperf Done.

C:\iperf>

**Comment by bmah888** [comment] 2015-11-16 19:25
Windows is not an officially supported platform.  I'm not even sure if the stock sources will build on Windows.  Perhaps someone else in the community who has tried this would be able to comment.

**Comment by bmah888** [comment] 2017-05-17 20:35
Closing...we have no idea what the problem is and no easy way to diagnose this unsupported platform.

**Closed by bmah888** 2017-05-17 20:35 UTC
Labels: Help Wanted, portability
